### ISSUE TITLE
Find people to be the point of contact for the workbook for each segment of the learning path. 

### ISSUE THREAD

**Issue by lenucksi** [InnerSourceCommons/InnerSourceLearningPath#103]
## Context
The learning path will have a workbook companion report.  :fireworks: 
Videos are broken into small segments. Before viewers go on to the next segment, the workbook gives them an opportunity to ask themselves multiple choice questions to make sure they got the videos’ takeaway.

## Required action
This will be a set of multiple choice questions dealing with the key take-aways per segment. We need someone to be responsible to collect and deliver them to O'Reilly per segment. O'Reilly can help to provide the wrong answers, we need to provide the questions and the right answers.

@clobner probably is interested in this ticket. Does Andy have a GitHub handle?

## Ticket purpose
This ticket is supposed to find the people, let's handle the actual collection in separate tickets then.

**Comment by rrrutledge** [comment]
I feel like we could just create the tickets now and then "finding" a person would just mean assigning the ticket to them in _GitHub_.

**Comment by lenucksi** [comment]
Here are a few updates: 
- Andy from O'Reilly created a [Google doc](https://innersourcecommons.slack.com/archives/CARTU4XV2/p1564535618029400) with quite some very nice content to start off of. 
- @maxcapraro might be interested in reviewing a few parts.
- The content will finally go into O'Reilly Atlas anyway, hence it was proposed to possibly just create it here and review it with the GitHub Review Workflow. Hopefully more on this to be discussed on the 8th's call. @clobner might have some updates then.

Create single tickets from this sounds like a good idea.

**Comment by rrrutledge** [comment]
If going into `Atlas` anyway then reviewing in _GitHub_ sounds great.  The PR/review process has a lot of advantages.

**Comment by lenucksi** [comment]
We've found people dealing with the workbook sections and opened the respective tickets for them, thus I'm closing this one here. 
Feel welcome to add your comments to the Google Doc as well, too!
