### ISSUE TITLE
Workbook review: Introduction

### ISSUE THREAD

**Issue by lenucksi** [InnerSourceCommons/InnerSourceLearningPath#104]
# Context
The learning path will have a workbook companion report.
Videos are broken into small segments. Before viewers go on to the next segment, the workbook gives them an opportunity to ask themselves multiple choice questions to make sure they got the videos’ takeaway.

# Action point
Review and propose changes (in the [Google doc](https://docs.google.com/document/d/1UXt3HsaGKDmVPcHIJYRolgrhC9hXJ6j9qzYVK1a_kwQ/edit?usp=sharing)) for the **Introduction Segment Questions**.
See #103 for details.

**Comment by rrrutledge** [comment]
There was a comment that I left here that were resolved without being acted on and the text I added was deleted without a trace ([example](https://docs.google.com/a/nike.com/document/d/1UXt3HsaGKDmVPcHIJYRolgrhC9hXJ6j9qzYVK1a_kwQ/edit?disco=AAAADPqZdqc)).  What happened?

**Comment by rrrutledge** [comment]
Another ([example](https://urldefense.proofpoint.com/v2/url?u=https-3A__docs.google.com_a_oreilly.com_document_d_1UXt3HsaGKDmVPcHIJYRolgrhC9hXJ6j9qzYVK1a-5FkwQ_edit-3Fdisco-3DAAAADPqZdqA-26usp-3Dcomment-5Femail-5Fdiscussion-26usp-5Fdm-3Dfalse-26ts-3D5d4c2f40&d=DwMFaQ&c=7DfhQjPWzR3PmWBQVpi-kw&r=uK7pDePvd6GZ3d-0Ou72DFQv2aXg-kpKNwGgw87rIKY&m=OsMuLGbxuyoN37OKNyzlchIEuVnygPjA-jkIhvS4qRI&s=Y1cwtMWfFkmrsCvLD8D6pvzqBkmpamF85aHOwuE7qnI&e=)).

**Comment by rrrutledge** [comment]
I can take a look as well.

**Comment by lenucksi** [comment]
Looks like we're done reviewing the introduction section. I'm moving that into our GitHub repo as ASCIIdoc from the Google Doc.

**Comment by tsadler1988** [comment]
Marked as 'Done' on the Project board but not closed. Can it be?

**Comment by rrrutledge** [comment]
Sounds good.
