### ISSUE TITLE
Workbook review: Trusted Committer Segment

### ISSUE THREAD

**Issue by lenucksi** [InnerSourceCommons/InnerSourceLearningPath#105]
# Context
The learning path will have a workbook companion report.
Videos are broken into small segments. Before viewers go on to the next segment, the workbook gives them an opportunity to ask themselves multiple choice questions to make sure they got the videos’ takeaway.

# Action point
Review and propose changes (in the [Google doc](https://docs.google.com/document/d/1UXt3HsaGKDmVPcHIJYRolgrhC9hXJ6j9qzYVK1a_kwQ/edit?usp=sharing)) for the **Trusted Committer Segment Questions**.
See #103 for details.

**Comment by rrrutledge** [comment]
Reviewed the first half of the section (segments 1-4).

**Comment by rrrutledge** [comment]
Need to provide answers for why the correct answers are correct.

**Comment by lenucksi** [comment]
Added minor reviews here.

**Comment by lenucksi** [comment]
Looks like we're done reviewing the introduction section. I'm moving that into our GitHub repo as ASCIIdoc from the Google Doc.

**Comment by tsadler1988** [comment]
Marked as 'Done' on the Project board but not closed. Can it be?

**Comment by rrrutledge** [comment]
I think that all such issues can be closed.
