### ISSUE TITLE
Workbook review: Product Owner segment

### ISSUE THREAD

**Issue by lenucksi** [InnerSourceCommons/InnerSourceLearningPath#106]
# Context
The learning path will have a workbook companion report.
Videos are broken into small segments. Before viewers go on to the next segment, the workbook gives them an opportunity to ask themselves multiple choice questions to make sure they got the videos’ takeaway.

# Action point
Review and propose changes (in the [Google doc](https://docs.google.com/document/d/1UXt3HsaGKDmVPcHIJYRolgrhC9hXJ6j9qzYVK1a_kwQ/edit?usp=sharing)) for the **Product Owner Segment Questions**.
See #103 for details.

**Comment by rrrutledge** [comment]
Finished reviewing.  Have a look!

**Comment by tsadler1988** [comment]
Marked as 'Done' on the Project board but not closed. Can it be?
