### ISSUE TITLE
Workbook creation: Contributor

### ISSUE THREAD

**Issue by lenucksi** [InnerSourceCommons/InnerSourceLearningPath#107]
# Context
The learning path will have a workbook companion report.
Videos are broken into small segments. Before viewers go on to the next segment, the workbook gives them an opportunity to ask themselves multiple choice questions to make sure they got the videos’ takeaway.

# Action point
Create questions (in the [Google doc](https://docs.google.com/document/d/1UXt3HsaGKDmVPcHIJYRolgrhC9hXJ6j9qzYVK1a_kwQ/edit?usp=sharing)) for the **Contributor Segment**.
See #103 for details.

There can be as few or as many questions as make sense to cover the key points of content.

**Comment by clobner** [comment]
@arnom-ms Here is the schedule we are working toward:

100% draft from Andy: 9/09
O’Reilly editorial review: 9/10–9/16
InnerSource community review/tech review: 9/17–9/30
Andy revises: 10/01–10/14
Final edits (if needed): 10/15–10/21
Production: 10/22–10/08
Final files: 11/08

With that in mind, it would be great to have draft questions in place by the end of next week (8/30), if possible.

**Comment by rrrutledge** [comment]
@arnom-ms thanks for these questions!  I finished reviewing them and left comments in the [Google doc](https://docs.google.com/document/d/1UXt3HsaGKDmVPcHIJYRolgrhC9hXJ6j9qzYVK1a_kwQ/edit?usp=sharing).  I'm excited to keep working on them together!

**Comment by lenucksi** [comment]
Added minor reviews here.

**Comment by rrrutledge** [comment]
I think this looks good except for possibly reviewing the *Mechanics of Contributing* section now that the [PR](https://www.google.com/url?q=https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/117&sa=D&ust=1570575407241000&usg=AFQjCNEiY2gpVUu6oQN4QT3FCpDiKdchcA) is available.

**Comment by lenucksi** [comment]
Closing this, since it's done.
