### ISSUE TITLE
Video Rehearsal

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#11]

**Comment by rrrutledge** [comment]
Rehearsal(s) expected in the last week of October.

**Comment by rrrutledge** [comment]
@mrsanz volunteers as a dedicated reviewer of this content. Others from the community are, of course, invited as well and may pitch in, but @mrsanz is there for sure.

**Comment by rrrutledge** [comment]
Here are recordings: https://paypalflow.slack.com/archives/CARTU4XV2/p1540575176005200

**Comment by lenucksi** [comment]
This done and can be closed.
