### ISSUE TITLE
Fix header levels for all articles

### ISSUE THREAD

**Issue by MaineC** [InnerSourceCommons/InnerSourceLearningPath#114]
http://docs.atlas.oreilly.com/writing_in_markdown.html#writing-markdown-for-htmlbook-Oytyf4

As noticed in the review of #101 we need to go over all articles after writing them to fix the header levels.

**Comment by rrrutledge** [comment]
Thanks for opening this issue, Isabel.

**Comment by lenucksi** [comment]
Results from #108 might help here.

**Comment by Ludmila-N** [comment]
After reading O'Reilly description, I see that I need to align all headers to a different level - doing so.

**Comment by lenucksi** [comment]
Closing this since it's in done now.
