### ISSUE TITLE
Move Introduction section to innersourcecommons.org

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#119]
Now that we have the approval from O'Reilly to host the articles and videos ourselves we should move the Introduction section to the innersourcecommons.org website.

After this move of one section is done we can see how people like it and then [move the others](https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/120).

Here is a link to the [videos folder](https://drive.google.com/open?id=1okjMUBW2_TAYN0_f8rTSsyXFk8W6kUK0)

**Comment by tsadler1988** [comment]
https://github.com/InnerSourceCommons/innersourcecommons.org/pull/86 covers the videos, but not the articles.

**Comment by rrrutledge** [comment]
We talked today in call and decided that we'd at least like to link to the article text in _GitHub_.  Maybe put the link underneath each video?

**Comment by lenucksi** [comment]
https://github.com/InnerSourceCommons/innersourcecommons.org/pull/126 addresses this. Needs some merging.

**Comment by tsadler1988** [comment]
Covered by https://github.com/InnerSourceCommons/innersourcecommons.org/pull/159.
