### ISSUE TITLE
Written outline

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#12]

**Comment by rrrutledge** [comment]
@ttyler01 interested in taking a crack (backed up by @mrsanz)

**Comment by maxcapraro** [comment]
I renamed this to `video outline` to avoid confusion (initially thought it is a duplicate of #27 ). Please feel free to rename if I misunderstood something.

**Comment by maxcapraro** [comment]
Renamed it back as #10 appears to be the video outline for "trusted commiter". Sorry.

**Comment by rrrutledge** [comment]
The idea was to produce an outline of the written content for quick review before taking the time for a  full-blown article.  Which I think we did at some point.

**Comment by lenucksi** [comment]
It's in done, thus can be closed.
