### ISSUE TITLE
Evaluate self-hosting and rendering tools for our learning path version

### ISSUE THREAD

**Issue by lenucksi** [InnerSourceCommons/InnerSourceLearningPath#121]
We want to self-host our content at some point in time and for this we need a tool that creates a nice site out of our markdown articles.

**Comment by arnom-ms** [comment]
I had a look at docFX, unfortunately there is no support for ASCIIDOC at this point. Due to this I believe docFX is out of the race for us for now.

**Comment by rrrutledge** [comment]
Thanks, Arno

**Comment by tsadler1988** [comment]
Might https://github.com/asciidoctor/jekyll-asciidoc be an option, given we're using Jekyll for innersourcecommons.org?

**Comment by rrrutledge** [comment]
Sounds good to me.

**Comment by lenucksi** [comment]
Looks like something we can use. :)
There's also the Hugo's, Sphinx's, mkdoc's etc. of this world. But I haven't had time to dig in them further, aside of Hugo which I'm using for my website happily. Looks like most approaches to ASCIIDoc will go through ASCIIdoctor. 

I'd be great to have a way to produce a website, PDFs and EPUBs off the same content in the end. But we can do that on a different tool chain later I guess. 
Looks like there's already a nice LaTeX backend for ASCIIdoc. We'll probably find something for EPUB too.

**Comment by rrrutledge** [comment]
I was imagining, too, that these would become a part of the innersourcecommons.org site, so not how a tool like _Hugo_ would be compatible with the existing work already done in Jekyll.

**Comment by lenucksi** [comment]
> I was imagining, too, that these would become a part of the innersourcecommons.org site, so not how a tool like _Hugo_ would be compatible with the existing work already done in Jekyll.

The _Hugo class of tools_ would full replace Jekyll resulting in effectively the same output after import of existing content however removing the need to deal with the security issues around Jekyll. 
Content administration effectively looks the same.
The _Sphinx, mkdocs etc. class of tools_ is more aimed at producing technical documentation sites, books and less classic websites and would be a separated product that could be integrated into our main site with the added benefit of providing epub, pdf and website in one - more along the lines of what O'Reilly's Atlas does. 

In the case of the first class we can and should probably remove some of the weirdness we face using maintained 2nd/3rd party GitHub Actions.

**Comment by rrrutledge** [comment]
Got it. Converting the whole of _innersourcecommons.org_ to _Hugo_ seems like a larger amount of work, so I'd be in favor of just adding our stuff into the existing _innersourcecommons.org_ using _Jekyll_.

**Comment by tsadler1988** [comment]
For https://github.com/InnerSourceCommons/innersourcecommons.org/pull/159, I used https://asciidoctor.org/docs/asciidoctor.js/. 

This approach means we can continue with Jekyll and markdown for the website, with the asciidoc articles embedded separately.

**Comment by rrrutledge** [comment]
We're happy with this approach, Tom.  Great work!
