### ISSUE TITLE
Check videos against workbook after creation

### ISSUE THREAD

**Issue by lenucksi** [InnerSourceCommons/InnerSourceLearningPath#122]
What we have left:

- [x] Upload new video.
- [x] Update references to new video (e.g. config.yaml, playlists).
- [ ] Rewrite question.

## Rationale
The [workbook] contains questions based on the videos - one could consider this the take-aways.
Especially in the case of the _Contributor_ we are creating [workbook] content before the videos based on the Outline and the articles. 
We need to ensure that the videos and articles contain content that matches the [workbook] questions and makes them properly answerable.

### Prior to making the videos
- Check that the _Contributor_ video scripts have matching content for the [workbook] 
### After making the videos
- Check the _Contributor_ videos for content from the [workbook]
### Acceptance:
- [ ] Let someone uninvolved test themselves with the [workbook] based on the videos.
 - [x] Introduction
    - [x] Seen Through
    - [x] Clean + Pass
    - [x] Adapted + Pass now
 - [x] Trusted Committer
    - [x] Seen Through
    - [x] Clean + Pass
    - [x] Adapted + Pass now
 - [ ] Contributor (Videos can be seen here: https://innersourcecommons.org/learn/learning-path/contributor/)
    - [x] Seen Through
    - [x] Clean + Pass
    - [x] Adapted + Pass now
 - [x] Product Owner
    - [x] Seen Through
    - [x] Clean + Pass
    - [x] Adapted + Pass now

[workbook]: https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/workbook

**Comment by rrrutledge** [comment]
We can also do this check _after_ creating the video scripts yet still _before_ shooting the video itself (https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/140)

**Comment by lenucksi** [comment]
Screenlight link available here: https://innersourcecommons.slack.com/archives/CARTU4XV2/p1573840051113600

**Comment by arnom-ms** [comment]
At this point the ask is to 
* Watch the video on one segment (available on our Google drive)
* After watching one segment, review the workbook questions if the question(s) for the segment can be answered after watching the video.

**Comment by rrrutledge** [comment]
Britany working on this.

**Comment by BrittanyIstenes** [comment]
Introduction - Video 3
- Planning role is not listed in guidance doc
- Additional resource page leads to a 404 

Introduction - Video 4
- Video script is more high level than the doc, but covers all the bases

Introduction - Video 5
- Mentorship is talked about in the video first, Openness is listed first in the doc
- 10% of resource into your trusted committer is not listed in doc
- Video only focused on Mentorship and Trusted committers, but did not get back into the other principles listed in the doc

**Comment by rrrutledge** [comment]
Here is the workbook: https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/workbook

Try out the assessment questions (no peeking).

**Comment by lenucksi** [comment]
> Introduction - Video 3
> * **Additional resource page leads to a 404**

Do we control said URL such that we could un-404 it?

**Comment by rrrutledge** [comment]
Which URL, specifically, are we talking about?

**Comment by BrittanyIstenes** [comment]
https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/project-roles/trusted-committer.asciidoc - This leads to the 404.

**Comment by lenucksi** [comment]
> https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/project-roles/trusted-committer.asciidoc - This leads to the 404.

Is that URL embedded into the video? In that case fixing it would be quite a bit more of an effort. 
If we have it in text in any of our repos, we could still fix it.

**Comment by rrrutledge** [comment]
It is in our repos.  Opened https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/251 to fix.

**Comment by BrittanyIstenes** [comment]
Introduction and Product Owner complete.  

Product Owner question "Roles and Responsibilities" was a tricky one.  The content in the video was super deep, and the wording didnt quite align from the video to the way that the question was phrased within the answer choices.  I mean, it did force me to rewatch the video to check the answer reasoning, but it was a hard one.

**Comment by rrrutledge** [comment]
Good call out.

**Comment by rrrutledge** [comment]
Some more feedback coming soon from Brittany

**Comment by BrittanyIstenes** [comment]
Trusted Committer videos were solid and Workbook followed suit.

**Comment by rrrutledge** [comment]
Great to hear!  Nice work, everyone!  🙌

**Comment by lenucksi** [comment]
Added a bunch of check boxes in the original ticket to track the state. Checked boxes according to what I've read here. Feel free to do some checkbox ticking as you see fit @BrittanyIstenes and thanks for reviewing! :smiley:

**Comment by rrrutledge** [comment]
Good point about the boxes.  Great way to track what's been done!

**Comment by BrittanyIstenes** [comment]
Team, to be honest, the question albeit confusing for me is probably not that way for many.  I personally think just leave it.  I do not have the best mind for creating in-depth questions like this one.

**Comment by rrrutledge** [comment]
OK!  Nice feedback.

**Comment by lenucksi** [comment]
Thanks @BrittanyIstenes!
From what I see then, this leaves the Contributor questions open for review.

**Comment by rrrutledge** [comment]
I agree with @BrittanyIstenes that the _Product Owner_ question wording is OK as-is.

**Comment by rrrutledge** [comment]
@mtabbal interested in looking at _Contributor_ [videos](http://innersourcecommons.org/resources/learningpath/contributor) vs. [workbook questions](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/workbook/04-contributor.asciidoc).

**Comment by lenucksi** [comment]
@Ludmila-N might be interested in doing the review for the last few videos and @lenucksi can put up the YT links to the videos next to the items.

**Comment by Ludmila-N** [comment]
Reviewing Contributor videos, so far the first two, I see a couple glitches with https://innersourcecommons.org/learn/learning-path/contributor/02/
1. The video: at about 3 min 23 sec, @lenucksi suggests that you can help by providing good bugs... I'm not sure this is what I want from my contributors :) 
2. The workbook: I cannot find any specific content in this video (or accompanying transcript) speaking to Question 2. What is a productive assumption for a contributor to make when joining an InnerSource project?
What are the ways we can address both/either of these?

**Comment by lenucksi** [comment]
> Reviewing Contributor videos, so far the first two, I see a couple glitches with https://innersourcecommons.org/learn/learning-path/contributor/02/

Thanks for reviewing!
> 
>     1. The video: at about 3 min 23 sec, @lenucksi suggests that you can help by providing good bugs... I'm not sure this is what I want from my contributors :)
> 
The intent here is "bug tickets" "well written issues". At least the good ones already help tremendously, so I definitely would want them. Where "well written" means: Detailed, with reproduction step, expectations and reality, possibly even a first patch or guess at a code location. Maybe we could add a small overlay on the video?

>     2. The workbook: I cannot find any specific content in this video (or accompanying transcript) speaking to Question 2. What is a productive assumption for a contributor to make when joining an InnerSource project?
> 
> 
> What are the ways we can address both/either of these?

Added a suggestion for the first. For the second one I think the intent of the question is in the correct answer and its explanation. Could we maybe replace or enhance the question so it fits the video and intent?

**Comment by Ludmila-N** [comment]
> The intent here is "bug tickets" "well written issues". At least the good ones already help tremendously, so I definitely would want them. Where "well written" means: Detailed, with reproduction step, expectations and reality, possibly even a first patch or guess at a code location. Maybe we could add a small overlay on the video?

Understood, and you say this in a few seconds - so this was provably a self-correction, but it sounds like you're listing bugs along with bug tickets. I think the best option is to cut or mute these ~5 seconds and leave the rest as is.

**Comment by Ludmila-N** [comment]
Reviewing Contributor videos, Contributor Ethos section:
Question 2 - no issues.
Question 1, answer 4 has the explanation that was never mentioned in the video, suggest rewriting this option: 
> Why 4 is incorrect: Getting your contribution accepted is an achievement to be celebrated. However, your involvement does not end there. You should plan to be available at a minimum to fulfil a 30-day warranty on your changes (and their impact), or even better: stay close to the community and help out with additional contributions.
Also "fulfill" is spelled with double L at the end.

**Comment by lenucksi** [comment]
> Understood, and you say this in a few seconds - so this was provably a self-correction, but it sounds like you're listing bugs along with bug tickets. I think the best option is to cut or mute these ~5 seconds and leave the rest as is.

Cutting it out sounds good. Do you happen to have taken a note of the time-code such that I can just edit it out and re-upload it?
Other than that: We'll need to update parts of the website, the playlists on YT or other material with the new video code. Can you please point me to the places that need chaninging @tsadler1988 @voborgus ?

**Comment by lenucksi** [comment]
"Providing good bugs" is at 3:25, "providing good issue tickets for bugs" is at 3:29
Modified video has been uploaded to the the GDrive. We need someone to re-upload it to YT, adapt the YT playlists, add the thumbnail and modify the website parts accordingly.

**Comment by rrrutledge** [comment]
Modified video: https://drive.google.com/file/d/1OXVUYR40AifTNKCDdMSRK82gtrpmUcft/view?usp=sharing

**Comment by clcoffey** [comment]
The modified video is now on Youtube https://youtu.be/S0Gps2AbZ7M courtesy of @katiegilroyy Can I just change the website directly to point it to the video or do you have to do it in your repository?

**Comment by lenucksi** [comment]
New video is live and adapted. Remaining is adaptation of the Workbook question

**Comment by rrrutledge** [comment]
Nice work!

**Comment by fioddor** [comment]
I've watched the _Introduction_ videos and I was able to complete their corresponding workbook. I'm totally uninvolved in their creation, but in the other hand I already have some previous knowledge about open source communities, so take my feedback with a pinch of salt.

**Comment by rrrutledge** [comment]
Thanks for this review @fioddor.

**Comment by rrrutledge** [comment]
@lenucksi can you update the checkboxes in the description with what has been done and what is left?
