### ISSUE TITLE
Check in workbook to Git

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#123]
After we have a set of workbook questions that we're happy with we should check them in to _git_.  The workbook content is under the same contract and sharing options as the other content in the Learning Path, and this sharing is made more clear by having it in the same repo and underneath the same open source license as the other material in the learning path.

The workbook questions for each section of the learning path should live under the respective folder in a document called `workbook.md`.

**Comment by rrrutledge** [comment]
We should also update the `README` to reference where the workbook markdown goes in the repo structure.

**Comment by rrrutledge** [comment]
Check this article to make sure if there's any special format needed for the workbook: http://docs.atlas.oreilly.com/writing_in_markdown.html#writing-markdown-for-htmlbook-Oytyf4

**Comment by lenucksi** [comment]
We need to keep in mind the O'Reilly layout requirements from #114.

**Comment by lenucksi** [comment]
All parts are transferred as pull requests now and ready for further processing:
 - Introduction: #185 
 - Trusted Committer: #186
 - Product Owner: #180 
 - Contributor: #189

**Comment by lenucksi** [comment]
All sections got merged into master, I guess this should close this.

**Comment by rrrutledge** [comment]
🎉

**Comment by lenucksi** [comment]
Closing as it's been moved to done.
