### ISSUE TITLE
Site structure for hosting learning path content on innersourcecommons.org

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#124]
We want to host all of the articles and videos being produced by the learning path on innersourcecommons.org.  Before just going ahead and doing the pull request we should agree at a high-level design of how we will change the innersourcecommons.org sitemap to host this new content.  In particular the plan should detail:

* What pages will we add or modify?
* What is the short description of what will be added or modified on each page?
* What links will we add between pages.

We should agree on this plan both within the [#learning-path](https://app.slack.com/client/T04PXKRM0/CARTU4XV2) and [#commonsgovernance](https://app.slack.com/client/T04PXKRM0/C53PG55RC) working groups.

**Comment by tsadler1988** [comment]
https://github.com/InnerSourceCommons/innersourcecommons.org/pull/86 assumes a structure of:

```
-resources/learningpath
  -- resources/learningpath/introduction
  -- resources/learningpath/productowner
  -- resources/learningpath/trustedcommitter
  -- resources/learningpath/contributor
```

With `resources/learningpath` modified to point to the self hosted pages, instead of O'Reilly, as they become available.

It doesn't include:
- Links between pages
- How to handle articles

**Comment by rrrutledge** [comment]
I'd be in favor of this with the small change of each section having its own set of sub-pages.  One page per each segment where the page hosts _both_ the video and article on the same page.  Thoughts?

**Comment by rrrutledge** [comment]
e.g.

```
-resources/learningpath
  -- resources/learningpath/introduction/introduction
    -- resources/learningpath/introduction/problems-solved
    -- resources/learningpath/introduction/how-works
    -- resources/learningpath/introduction/benefits
    -- resources/learningpath/introduction/principles
    -- resources/learningpath/introduction/conclusion
```

**Comment by rrrutledge** [comment]
Update -  we'd like to start with @tsadler1988's suggestion and then later on move to my more-complicated suggestion.  Opened [Inline article text on innersourcecommons.org](https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/224) to track the more-complicated suggestion.

**Comment by tsadler1988** [comment]
Covered by https://github.com/InnerSourceCommons/innersourcecommons.org/pull/159.
