### ISSUE TITLE
 O’Reilly to update the LICENSE.txt to existing documents

### ISSUE THREAD

**Issue by arnom-ms** [InnerSourceCommons/InnerSourceLearningPath#127]
As we have added the CC-BY 4.0 license to existing learningpath documents, O'Reilly should add their addendum as they see needed to the license via PR.

See also issue https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/66

**Comment by lenucksi** [comment]
CC-BY-SA 4.0 license file is here: https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/LICENSE.txt

**Comment by rrrutledge** [comment]
O'Reilly had a look and think that what is there is good.

**Comment by lenucksi** [comment]
> O'Reilly had a look and think that what is there is good.

Does that mean that this ticket would be ready to be closed?

**Comment by clobner** [comment]
Yes, I think we can close this.

**Comment by rrrutledge** [comment]
🎉 Thank you!
