### ISSUE TITLE
Slides for the contributor segment

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#130]
We should make slides to accompany the "Introduction" video in the "Contributor" section of the learning path.  These slides should follow the format of [other section slides](https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/assets/segment-04-po) and be submitted via pull request.  All of the slides were created from this [ODP file](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/assets/segment-04-po/PO%20Video%20Slides.odp).

**Comment by MaineC** [comment]
What is the font being used in the other learning path slides?

**Comment by MaineC** [comment]
Except for the question about fonts, I've started a document to work on the slides over there:

https://docs.google.com/presentation/d/1FfZc1ObSoITta3UBIxPEBgEyj1z_w3l_Y3kPb-oRGOc/edit?usp=sharing

**Comment by rrrutledge** [comment]
:cool:, Isabel.  I updated the description with a link to the original ODP file that produced the images.  Does that help?

**Comment by rrrutledge** [comment]
Once we have the videos available in screenlight we need to mark when we want the slides appearing (start and end times and what slide appears).

**Comment by lenucksi** [comment]
Screenlight link available here: https://innersourcecommons.slack.com/archives/CARTU4XV2/p1573840051113600

**Comment by lenucksi** [comment]
Pull request (currently WIP) adding the slides converted to PDF added here: #196 
Will be updated and contain the final PPT/ODP in the end.

**Comment by lenucksi** [comment]
Please conduct the review and suggestions for the slides as follows:

Look for:
- Typos
- Improvement suggestions to text or missing slides found in the videos or that you think would be useful
Approach:
- It's a Google Slides document, please add a Google annotation if you think something should be changed at what you think should be changed. 
- Please add an annotation if you added a slide explaining the rationale.
- Try using the mention feature on Google slides if you want.
- You are welcome to post links to the annotations here.

**Comment by Ludmila-N** [comment]
30 Jan 2020: asking o'Reilly (Kirsten) to change the fonts, and this should conclude the work.
