### ISSUE TITLE
"Contributor" section rehearsal

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#132]
We should do a rehearsal of the videos in the "Contributor" section of the learning path.  This rehearsal will give community members a chance to give feedback before the final video shoot.

**Comment by lenucksi** [comment]
We'll likely have the opportunity this starting from around late noon CEST this next week, i.e. 28th of October. 
Format will be video + document to collect feedback. Posting here and in the channel once available

**Comment by rrrutledge** [comment]
Sounds great.  Thank you!

**Comment by lenucksi** [comment]
Recording one did not really work due to time constraints. I've managed to do a quick one with Russ and got some feedback - hopefully some of it was incorporated into the filmed content.
