### ISSUE TITLE
O'Reilly edits to "Introduction" articles.

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#138]
Now that the [introduction articles](https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/introduction) are done they should be sent over to the [O'Reilly _Atlas_ repo](https://atlas.oreilly.com/oreillymedia/introduction-to-innersource) so that the O'Reilly editors can take a look.

**Comment by rrrutledge** [comment]
@clobner can you confirm that link in the description is where you want the markdown of the articles?

**Comment by clobner** [comment]
@rrrutledge That link is correct. Thank you for checking!

**Comment by lenucksi** [comment]
I was wondering if it would be possible to re-use our repo structure and configure the atlas.json to include the right files from the right directories. 
That would allow us to just sync the content over to your repo, merge in your template and atlas.json and be done with it keeping everything syncable and intact facilitating the expected review round-trips a bit I'd think. 
The alternative would be to check out both repos, copy over our introduction directory .md files and be done - however requiring manual action upon every change.

I've just executed the second version to see the result without any changes and instantly got the nice layout. However, there obviously is the need to edit & configure around a bit and also review the content after that. 

Take a look at the scripts/tested approach published here: https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/108#issuecomment-536203191

**Comment by lenucksi** [comment]
No changes found that could be merged. Closing this ticket.

**Comment by rrrutledge** [comment]
Great.  Thanks for having a look.
