### ISSUE TITLE
Review workbook questions for fidelity with scripts

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#140]
After the workbook questions and the video scripts are finished Andy can review the workbook questions to make sure that they look good and fair to ask given the scripts that we have prepared.

This step would be good to take so that we can make any adjustments to the script _before_ filming so that we are enabled to ask the questions that we want to ask for the takeaways.

**Comment by rrrutledge** [comment]
We will also do this same check after shooting the video itself (https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/122)

**Comment by lenucksi** [comment]
The videos have been shot now, so we're going to check against them directly as @rrrutledge wrote. Closing this in favor of #122 then.
