### ISSUE TITLE
Professional Design of Workbook

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#141]
O'Reilly is going to get a designer to contribute to the look and feel of the workbook.  Tracking that initiative via this issue.

**Comment by rrrutledge** [comment]
Must have fat-fingered it.  Sorry!

**Comment by clobner** [comment]
Sharing a preview of how we've reformatted the first section:
[http://orm-atlas2-prod.s3.amazonaws.com/pdf/1ef92876958e434978cdff73.pdf](http://orm-atlas2-prod.s3.amazonaws.com/pdf/1ef92876958e434978cdff73.pdf)

The production editor broke it up into Questions and Answers, and demoted all headings by one to make it look nicer.  We welcome your thoughts and suggestions!

**Comment by rrrutledge** [comment]
Fun!  Thanks for this preview.

Is there an interactive format as well (website with multiple choice / radio buttons)?

**Comment by clobner** [comment]
There will be, yes! We'll be digging into the assessment version next week as we get closer to finalizing the content. Excited to share more details next week.
