### ISSUE TITLE
Written Outline

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#15]
Consistent with other sections of the learning path, we should create an `outline.md` document for _Product Owner_.  It can be based on the existing videos and transcripts and should encompass the breadth (but not depth) of what we want to say about each segment in the _Product Owner_ section of the learning path.

After the outline is complete we should open up individual tickets representing the full-written articles for each video.

**Comment by rrrutledge** [comment]
@Silona interested in authoring

**Comment by rrrutledge** [comment]
@maxcapraro as dedicated reviewer.

**Comment by rrrutledge** [comment]
Silona thinks that she can start making progress on authoring the week of the 21st.

**Comment by rrrutledge** [comment]
Here is [the transcript](https://docs.google.com/document/d/1mRqfonedtzEc2kJ6wy-jx0SfdHa_IuwM8NDQguRh5Co) for the videos in case it's useful when starting this work.

**Comment by lenucksi** [comment]
#96 has a PR for the PO outline mentioned here.

**Comment by RJPlog** [comment]
not needed any more, #265 -- #270 will deal with this issue --> will be closed
