### ISSUE TITLE
Create an O'Reilly offering that presents all sections of the learning path as one

### ISSUE THREAD

**Issue by lenucksi** [InnerSourceCommons/InnerSourceLearningPath#167]
Currently the learning path is presented as four different and possible but not visibly related products in learning.oreilly.com. 
We want to have an opportunity to enable presentation of the 4 learning path sections as one, or to have them perceived as belonging together.

**Comment by rrrutledge** [comment]
Great summary!

**Comment by rrrutledge** [comment]
Colleen to share a proposal of the section/segment ordering

**Comment by lenucksi** [comment]
Could you write-up a proposal how the unified offering would be great to look like and what problems might still be open, @rrrutledge?
- Such as "Have the one link to bind them all?"

**Comment by lenucksi** [comment]
We forwarded our description, title and additional information on the all-in-one to @DanGitOreilly.
According to Dan, they plan to get this done around the end of this month.

**Comment by rrrutledge** [comment]
Great to hear!

**Comment by rrrutledge** [comment]
Done!  Thanks, Dan!
https://learning.oreilly.com/learning-paths/learning-path-innersource/0636920438137/

**Comment by lenucksi** [comment]
I think we can close this as it is done.

**Comment by lenucksi** [comment]
This https://github.com/InnerSourceCommons/innersourcecommons.org/pull/169 changes our website to the new URL.
