### ISSUE TITLE
Draft comments in article texts

### ISSUE THREAD

**Issue by Ludmila-N** [InnerSourceCommons/InnerSourceLearningPath#170]
All articles in contributor section and introduction/06-conclusion.md have draft comments on top, before the article actually begins. Shall we remove them, or are they being used (and subsequently removed) by O'Reilly team during final edits?   
Russ - I can remove them so long as you confirm.

**Comment by lenucksi** [comment]
Those draft parts are not needed anymore and were part of the creation process to ensure that the outlined points are met. 
Feel welcome to create removal PRs!

**Comment by Ludmila-N** [comment]
Thank you @lenucksi !
Done with changes - although couldn't figure out the new PR since my prior one is open. So changes for this issue are in the same PR#169 with article links.

**Comment by rrrutledge** [comment]
This is amazing work, @Ludmila-N.

**Comment by lenucksi** [comment]
This is done and merged now :D
