### ISSUE TITLE
Style review for Contributor articles

### ISSUE THREAD

**Issue by Ludmila-N** [InnerSourceCommons/InnerSourceLearningPath#182]
Review for Contributor articles for written style conformance

**Comment by rrrutledge** [comment]
Sounds great.

**Comment by Ludmila-N** [comment]
question to @rrrutledge and @lenucksi 
The 03-contributor-ethos-article has the following paragraph that I have hard time rephrasing because I don't know what the piece **_in bold_** is trying to deliver.

_Here's my general rule of thumb: feel free to meet over coffee. Often that helps 
build a stronger team. **Remember though that when the team is split into
multiple physical locations (for me that includes teams that are spread across
mutliple floors), there is a good chance that this encourages the team to split
into multiple silos.** Do make sure though that all decisions are made in a
transparent and asynchronous way so that everyone - including those lurking in
on your conversation - can jump in and become active contributors._ 

I would like to remove it altogether, or else tell me how this passage helps clarify the point that
a) meeting in person is great for relationships
b) but project documentation has to be kept in writing  
Appreciate your direction!

**Comment by lenucksi** [comment]
I read this, based on my experience, as the following: This is a practical example of which little things might suffice to create division, a feeling of separation, etc. that will lead to "group think", i.e. Silos.
It doesn't have to be the Atlantic or the Baltic sea separating people, sometimes a ceiling is entirely sufficient.

We might want to consider replacing or explaining [lurking](https://en.wikipedia.org/wiki/Lurker) here. I know what it means, is this common knowledge though?

**Comment by Ludmila-N** [comment]
#201 concludes the work and is open for review.

**Comment by Ludmila-N** [comment]
All PRs for this issue are merged - I propose to close this issue now. Many thanks!

**Comment by lenucksi** [comment]
> All PRs for this issue are merged - I propose to close this issue now. Many thanks!

Thanks for this, I was going to ask. Also, thanks for doing this! :D
