### ISSUE TITLE
Submit slides (w/ timings) to O'Reilly

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#184]
After we finish creating the [_Contributor_ slides](https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/130) we need share slide-by-side to O'Reilly when the slides should appear and in what videos.

We can do this by leaving comments at the appropriate timestamps in the _Screenlight_ tool (link forthcoming).  We should already have the slides checked in to our repo by this point and so can just link to the desires slide at the appropriate timestamp in _Screenlight_.

**Comment by lenucksi** [comment]
Screenlight link available here: https://innersourcecommons.slack.com/archives/CARTU4XV2/p1573840051113600

**Comment by lenucksi** [comment]
Pull request (currently WIP) adding the slides converted to PDF added here: #196 
Will be updated and contain the final PPT/ODP in the end.
