### ISSUE TITLE
Decide where to host the videos

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#206]
In order to get the videos onto our web site we need to decide where we're going to host them.

They are currently in [this GDrive](https://drive.google.com/drive/folders/1okjMUBW2_TAYN0_f8rTSsyXFk8W6kUK0?usp=sharing).

**Comment by rrrutledge** [comment]
Suggest hosting in the [InnerSource Commons YouTube channel](https://www.youtube.com/channel/UCoSPSd6Or4F_vpjo4SmyoEA)

**Comment by rrrutledge** [comment]
I think that @NewMexicoKid may know how to get access.

**Comment by lenucksi** [comment]
We decided for YouTube.
