### ISSUE TITLE
Update links to point to self-hosting location

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#207]
We have links in our articles cross-referencing them to other  articles.  Right now that is the GitHub location, but after we publish our written articles to InnerSourceCommons.org we should update those cross-references to point at that InnerSourceCommons.org location.

**Comment by lenucksi** [comment]
Pull request #220 is part of solving this.

**Comment by arnom-ms** [comment]
Currently blocked. The goal is to have it properly render it on InnerSource Commons web page instead of just pointing to GitHub.

**Comment by tsadler1988** [comment]
InnerSourceCommons/innersourcecommons.org#159 links will point to GitHub. Once #246 has been merged, we can update the self-hosted articles to link to other self-hosted articles.
