### ISSUE TITLE
Post Production: Contributor videos final review and acceptance

### ISSUE THREAD

**Issue by Ludmila-N** [InnerSourceCommons/InnerSourceLearningPath#213]
This issue covers the review of the final videos for Contributor section

**Comment by Ludmila-N** [comment]
Related work items: #68 #70 #71 #73 #75 #77 
Once O'Reilly has addressed the comments made in the 6 respective segments, we need to do one final review of the finished product.

**Comment by lenucksi** [comment]
O'Reilly has released the videos to us and hence the post production and review on their side is finished. We should close this.
