### ISSUE TITLE
Translate Introduction articles to German

### ISSUE THREAD

**Issue by arnom-ms** [InnerSourceCommons/InnerSourceLearningPath#217]
In order to increase reach and ease consumption of the articles a translation to languages with broad reach is desired. This is the issue for GERMAN translation of the Introduction article series. 

Localized articels should be stored under an folder that carries the ISO639-1 defined string. (https://www.loc.gov/standards/iso639-2/php/code_list.php)

**Comment by lenucksi** [comment]
Created an umbrella issue for translations: #219
