### ISSUE TITLE
Translations are welcome! See here for more information.

### ISSUE THREAD

**Issue by lenucksi** [InnerSourceCommons/InnerSourceLearningPath#219]
# Translations very welcome!
Would you like to see our material translated to your native language to allow it to reach more people?
We also would love to see that! 
However, we don't speak every language and would love to host any translation you may want to contribute - and help you with everything around making it as far as we can.

## What you can do
- Add a request for your language if it is not present yet as a comment. If it is already present, please add a thumbs up to it.

- Start a new translation
  - If you want to start a new translation, please get in contact with us using our [Slack](http://innersourcecommons.org/slackinvite).

- Help with improving an existing translation 
  - If you want to improve an existing translation, please go ahead and file a pull request for the improvements you would like to make. You are also very welcome to contact us via Slack first if you would like to.
  - We currently use this pull request to elaborate on [how to store translations](https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/218#issuecomment-590845024).

**Comment by lenucksi** [comment]
## Existing translations

## Translations being created currently
- German: #217

**Comment by rrrutledge** [comment]
This is awesome!  Add to README or CONTRIBUTING?

**Comment by lenucksi** [comment]
> This is awesome! Add to README or CONTRIBUTING?

I think we can (and should) also do that, but I'd leave this here for voting purposes and as an active reminder too. 
Would you mind filing a PR for the file changes?

**Comment by rrrutledge** [comment]
I will try.

**Comment by rrrutledge** [comment]
Documenting this at https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/257.

**Comment by lenucksi** [comment]
Probably would be good to change the original issue to reflect the Wiki-Page. 
Maybe even adding a link from the wiki start page to the translation page would be good.

**Comment by rrrutledge** [comment]
Is this issue still needed or should people just look at `CONTRIBUTING.md`?

**Comment by lenucksi** [comment]
> Is this issue still needed or should people just look at `CONTRIBUTING.md`?

Fair point. Let's just close this then.
