### ISSUE TITLE
Create Tone of Voice

### ISSUE THREAD

**Issue by MaineC** [InnerSourceCommons/InnerSourceLearningPath#222]
As we move towards translated versions and as more than one author is working on the Learning Path it would be great to define a tone of voice for the InnerSource it:

* How formal do we want to talk with those listening/ reading?
* Who are we creating this learning path for?
* Which general topics are we writing about?
* What is the general structure of a Learning Path video, article, etc. (likely we have that already?)

**Comment by rrrutledge** [comment]
> Which general topics are we writing about?

What does this mean?  The scope is defined already at innersourcecommons.org/learningpath ?

**Comment by MaineC** [comment]
What I had in mind was something like a short section in e.g. the contributing.md where we can point contributors who are just about to get started. Likely that specific point is already covered in the README as well, so we can either leave it out or link to it.

**Comment by rrrutledge** [comment]
Got it.

**Comment by tsadler1988** [comment]
We're going to close this for now due to the number of articles and translations - we think we've left this too late now! However, this is definitely something to consider if we do a refresh of our articles in the future.
