### ISSUE TITLE
Finish URL mapping table

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#229]
https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/220 creates the schema for a table that maps related URLs together.  Now that we have a schema that we like, we need to get _all_ of the URLs in the learning path in there (not just the two beginning samples).

Please run YAMLlint against the file before submitting a PR.

Acceptance Criteria: All URLs from all segments of the learning path are in the URL mapping table.

**Comment by lenucksi** [comment]
@Ludmila-N wanted to take a look at the merged PR in #220 hence, giving this ticket to her.
Please close it once you deem it done @Ludmila-N! :)

**Comment by Ludmila-N** [comment]
Questions to either @rrrutledge or @lenucksi : 
1. Assume this will stay open until we are done with all articles, at least in the trusted committer section?
2. Not sure  how to deal with O'Reilly anchors which we are replacing back with links to the articles. I entered the full expression that I replaced with link to github article, like this: "pass:[<a data-type="xref" href="advocating" data-xrefstyle="chap-num-title">#advocating</a>]" - see PR #239 

Please correct me if this is not what "anchor" section meant, AND, if so, where do I put the above code. I felt like inserting just the anchor name (#advocating) will not give us the mapping we aimed for (ie, the ability to exactly replace code sections from O'Reilly to ISC).

**Comment by lenucksi** [comment]
> Questions to either @rrrutledge or @lenucksi :
> 
>     1. Assume this will stay open until we are done with all articles, at least in the trusted committer section?
> 
>     2. Not sure  how to deal with O'Reilly anchors which we are replacing back with links to the articles. I entered the full expression that I replaced with link to github article, like this:
> 
> 
> `"pass:[<a data-type="xref" href="advocating" data-xrefstyle="chap-num-title">#advocating</a>]" `
> (see PR #239 )
> 
> Please correct me if this is not what "anchor" section meant, AND, if so, where do I put the above code. I felt like inserting just the anchor name (#advocating) will not give us the mapping we aimed for (ie, the ability to exactly replace code sections from O'Reilly to ISC).

I've seen that in stead of our links in the material so I think your approach should work.

**Comment by rrrutledge** [comment]
Anchors look good.  I think that we should open up new issues (or just make new PRs) as new URLs come available.  Close this issue.

**Comment by Ludmila-N** [comment]
per comments
