### ISSUE TITLE
Update to videos without O'Reilly branding

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#238]
As part of the new CC-BY-SA contracts, O'Reilly wants to give us videos without any O'Reilly branding on them.  When we have them we should put those videos up on our YouTube channel and ISC website.

**Comment by lenucksi** [comment]
Those videos have been provided by O'Reily and are now uploaded to YT with the great help of @dicortazar. [#neuland](https://www.youtube.com/watch?v=-VkLbiDAouM).

**Comment by rrrutledge** [comment]
Great!  We need still need them on the ISC website, though.

**Comment by rrrutledge** [comment]
Going to wait for [Inline article text on innersourcecommons.org](https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/224) to merge first so we don’t get conflicts.

**Comment by tsadler1988** [comment]
Mentioned to @rrrutledge that it would be good if innersourcecommons.org read `urls.yaml` to get its YouTube URLs, rather than being hardcoded. I will look at getting that done in the next few days. Would it be part of this issue (the other part being to update `urls.yaml`)?

**Comment by rrrutledge** [comment]
Works for me, Tom.  Thanks for taking a look.

**Comment by tsadler1988** [comment]
See https://github.com/InnerSourceCommons/innersourcecommons.org/pull/171.

If that gets merged, you can get the new videos on the website simply by updating `urls.yaml`.

**Comment by lenucksi** [comment]
> See [InnerSourceCommons/innersourcecommons.org#171](https://github.com/InnerSourceCommons/innersourcecommons.org/pull/171).
> 
> If that gets merged, you can get the new videos on the website simply by updating `urls.yaml`.

Very nice, that just got merged. Possibly of interest for @BrittanyIstenes too?

**Comment by lenucksi** [comment]
This is done too, hence closing the issue.
