### ISSUE TITLE
Video link needs to be updated on site

### ISSUE THREAD

**Issue by BrittanyIstenes** [InnerSourceCommons/InnerSourceLearningPath#240]
https://www.youtube.com/watch?v=CxsfR_n7JKI&feature=emb_err_watch_on_yt - Need to go to youtube to actually watch this video.  Should it be dynamically linked in the site?

http://innersourcecommons.org/resources/learningpath/introduction/

![image](https://user-images.githubusercontent.com/50678820/79145947-89910780-7d8f-11ea-8907-5588ffadac8e.png)

**Comment by rrrutledge** [comment]
Adjusted permissions so it can be played in place.
