### ISSUE TITLE
Self-host non-English articles

### ISSUE THREAD

**Issue by tsadler1988** [InnerSourceCommons/InnerSourceLearningPath#249]
https://github.com/InnerSourceCommons/innersourcecommons.org/pull/159 only self-hosts the English versions of the articles.

**Comment by rrrutledge** [comment]
Exciting!  Thanks for taking this on, @tsadler1988 and @BrittanyIstenes!

**Comment by rrrutledge** [comment]
Is there a way to generate _embed_ URLs that auto-activate a language-specific captioning?  If so, then we can include the videos along with the articles on innersourcecommons.org.

**Comment by tsadler1988** [comment]
> Is there a way to generate _embed_ URLs that auto-activate a language-specific captioning? If so, then we can include the videos along with the articles on innersourcecommons.org.

https://support.google.com/youtube/answer/171780?hl=en-GB

> Make captions automatically appear on an embedded video by adding '&cc_load_policy=1' to the video's embed code.
> 
> You can also choose a caption language for the embedded video. To specify the caption language for the video that you'd like to embed, just add '&cc_lang_pref=fr&cc_load_policy=1' to the video's embed code.
> 
> - 'cc_lang_pref' sets the language for the captions shown in the video.
> - 'cc_load_policy=1' turns captions on by default.
> - 'fr' represents the language code for French. You can look up two-letter language codes in the ISO 639-1 standard.

**Comment by rrrutledge** [comment]
Great, Tom!  So we can include language-specific page of the learning path on _innersourcecommons.org_.

**Comment by rrrutledge** [comment]
Opened https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/306 to adjust the generation script for translated articles and https://github.com/InnerSourceCommons/innersourcecommons.org/pull/206 to display them on innersourcecommons.org

**Comment by lenucksi** [comment]
This is done now, closing.
