### ISSUE TITLE
Translate "Trusted Committer" articles to Chinese

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#252]
It's great to have the "Introduction" section [translated in Chinese](https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/introduction/zh).  Let's do the same for the ["Trusted Committer" section](https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/trusted-committer).

Similar to "Introduction", translations should be located in a `zh` folder.

**Comment by rrrutledge** [comment]
@adadai88 interested in this.

**Comment by yvonneT1** [comment]
Hello, I am yvonne, and I will be responsible for this translation now, I hope to make you satisfied. By the way, when is the expected completion date?

**Comment by yvonneT1** [comment]
Hey Russ,I am yvonne,just let you know I will do this translation with Ada.Do you have a due date for it？

**Comment by rrrutledge** [comment]
Yvonne, we are so happy that you are here.  We do not have a due date.  Let us know do you have a particular time that you are thinking of working on it?

**Comment by rrrutledge** [comment]
Hello, Yvonne, we are so glad that you are interested in doing this translation.  We had a call for this project yesterday and we let people know of your intent to work on it.  Please let us know how it is going when you have a minute.
