### ISSUE TITLE
Translate "Contributor" articles to Chinese

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#253]
It's great to have the "Introduction" section [translated in Chinese](https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/introduction/zh).  Let's do the same for the ["Contributor" section](https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/contributor).

Similar to "Introduction", translations should be located in a `zh` folder.

**Comment by rrrutledge** [comment]
@adadai88 interested in this.

**Comment by niminghong** [comment]
Hey Russ,I am with Ada and I would like to take this part, I have done 50% of articles offline , will finish and pull request accordingly :) 

Do you have a due date for it?

**Comment by niminghong** [comment]
Hey Russ,I am with Ada and I would like to take this part, I have done 40% of articles offline , will finish and pull request accordingly :)

Do you have a due date for it?

**Comment by rrrutledge** [comment]
Hello, @niminghong, we are glad that you are here!  It is great to hear that you have been working on the articles.  Looking forward to your pull request!  We do not have a due date for the articles - just let us know when you are getting close.

**Comment by niminghong** [comment]
I have translated 5 articles so far and i will let you know when i am getting close ;p

**Comment by rrrutledge** [comment]
Sounds like great progress!

**Comment by lenucksi** [comment]
> I have translated 5 articles so far and i will let you know when i am getting close ;p

Sounds great! Thanks for doing this :smile: !

**Comment by rrrutledge** [comment]
Hello, @niminghong , we are so glad that you are interested in doing this translation.  We had a call for this project yesterday and we let people know of your intent to work on it.  Please let us know how it is going when you have a minute.

**Comment by rrrutledge** [comment]
https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/275

Wow!

**Comment by lenucksi** [comment]
This pull request got merged so this is done :tada:!
Thanks again to @niminghong and everyone else involved.
