### ISSUE TITLE
Translate remaining "Trusted Committer" articles to German

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#256]
It's great to have the "Introduction" segment of the "Trusted Committer" section [translated in German](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/trusted-committer/de/01-introduction.asciidoc).  Let's do the same for the other articles in the ["Trusted Committer" section](https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/trusted-committer).

- [x] introduction

- [x] ensuring product quality

- [x] keeping the community healthy

- [x] uplevelling community members

- [x] lowering the barriers to entry

- [x] advocating for the community Needs

- [ ] becoming a trusted committer

- [x] conclusion

**Comment by lenucksi** [comment]
#317, #315, #311 address more segments.
