### ISSUE TITLE
Engaging landing page

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#260]
Our current [landing page](https://innersourcecommons.org/resources/learningpath/) doesn't really do justice to the work and value of the learning path.  We should make a more ... engaging landing page that really draws people in and helps them to understand what is the learning path, why it's awesome, and gets them excited to watch it.

**Comment by rrrutledge** [comment]
Take a look at https://docs.google.com/document/d/1KlUDIXyyqzvLdcdgXa6f2EmCCB39D6YUrUA3ElPRXNc/edit?usp=sharing

**Comment by claredillon** [comment]
There is a PR waiting for review and merge which covers the text changes. https://github.com/InnerSourceCommons/innersourcecommons.org/pull/173 

Danese approved changing order of roles presented. Had issues adding the images - but @lenucksi will help me with that as a second change (thanks Johannes).

**Comment by lenucksi** [comment]
We now definitely do have a more engaging landing page! :smiley: :tada:

**Comment by rrrutledge** [comment]
Agreed 🙂 ❗
