### ISSUE TITLE
Remove links to O'Reilly-hosted videos on innersourcecommons.org

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#273]
Now that we have all of our learning content hosted on _innersourcecommons.org_, we can just promote that version and not worry about linking back to O'Reilly.  Let's just have links to content on the innersourcecommons.org website.

We should probably wait until we're [self-hosting the non-O'Reilly versions](https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/238) of the videos before making this change.

**Comment by claredillon** [comment]
I've done a PR to change Learning Path landing page which removes these links - it's waiting for review/commit

**Comment by lenucksi** [comment]
> I've done a PR to change Learning Path landing page which removes these links - it's waiting for review/commit [InnerSourceCommons/innersourcecommons.org#173](https://github.com/InnerSourceCommons/innersourcecommons.org/pull/173)

This is merged now. Does this change this do done?

**Comment by rrrutledge** [comment]
I think so.  The links are gone.
