### ISSUE TITLE
Project Schedule

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#28]
It's fun to work together on the learning path, but we also want the work to come to an end and to finish it together!  A natural target for finishing would be the upcoming ISC Spring Summit in Ireland.  Let's put down a rough schedule of what we'd  need to do to finish all expected videos and articles and have them published on innersourcecommons.org and O'Reilly Safari at that point.

**Comment by rrrutledge** [comment]
Would like to have this ready for review for the January 10th working group meeting.

**Comment by rrrutledge** [comment]
Please see https://docs.google.com/document/d/1QtjQ-qy9bBaPob3V1OldjENTqvj6USIQCjMomKs0XEQ/edit

**Comment by lenucksi** [comment]
It's in done, thus we should close it.
