### ISSUE TITLE
Translate "Introduction" articles to Japanese

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#281]
Translate the [Introduction](https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/introduction) section into Japanese.

**Comment by rrrutledge** [comment]
https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/279

**Comment by lenucksi** [comment]
> #279

This pull request got merged, hence this work is done. 
Thanks again to @ystk and @johtani!

**Comment by rrrutledge** [comment]
I think that not all of the articles were translated yet.

**Comment by ystk** [comment]
I use my spare time to translate the articles. I may need a couple of weeks to finish all translations for the introduction section.
I make PR for each article to show some progress and also get someone's review here. If this makes confusion, please let me know.

**Comment by rrrutledge** [comment]
This is no problem, @ystk.  You are doing great!

**Comment by lenucksi** [comment]
> I think that not all of the articles were translated yet.

Looks like I missed that - thanks for noticing and re-opening! :smile:

**Comment by lenucksi** [comment]
> This is no problem, @ystk. You are doing great!

Exactly this! Thank you for your work translating this! :+1:  :tada: 
If you mention this issue number in your commit messages like "part of #281" the resulting pull request should automatically be linked here.

**Comment by rrrutledge** [comment]
Articles 1-4 are done.  Wow!

**Comment by claredillon** [comment]
@ystk working on 5&6 this week and next.

**Comment by claredillon** [comment]
When @ystk finishes translations, he will make a PR.

**Comment by rrrutledge** [comment]
@ystk finished number 5!!

**Comment by lenucksi** [comment]
Very impressive! :smiley:

**Comment by rrrutledge** [comment]
Amazing!

**Comment by lenucksi** [comment]
Everything is complete, thanks!
