### ISSUE TITLE
Next batch of segments

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#289]
We have some great content in the #learning-path that we're spreading far and wide.  As we're doing that we also need to continue to create new content!  Let's find a set of community-backed ideas for more training content on InnerSource.

Some places to find ideas:
* See what curated patterns are coming out of the InnerSource patterns community.
* Look at comments and discussion in this _GitHub_ [issue](https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/62) and [PR](https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/52)
* See what things people are talking about in _Slack_.

**Comment by lenucksi** [comment]
We've moved this since we're moving on with #350 in the spirit of this ticket.
