### ISSUE TITLE
Where to place our content

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#290]
We've produced great content and more will come.  How should it be placed  Obviously we have it on the ISC website, but it's kind of neat to have it in the O'Reilly learning platform as well.  Are there other training or hosting platforms where we'd like our videos and articles to show up?  Other places that should have links and references to it?  Let's figure out what those are so that as we continue to make more we can be purposeful about placing it.

**Comment by rrrutledge** [comment]
Marketing folks are working on this - we should get at least monthly updates on how it's going.

**Comment by mishari** [comment]
Terribly sorry, dropped the ball on this.
There's a learning path on the O'Reilly platform here, is there more content to add?
https://learning.oreilly.com/learning-paths/learning-path-innersource/0636920438137/

**Comment by rrrutledge** [comment]
Thanks for writing, @mishari.  That is all of the content that we have at present. We may make more in the future.  Even fir the content that we have, the question is if we should make it available in other hosting platforms (for increased visibility).

**Comment by lenucksi** [comment]
> Terribly sorry, dropped the ball on this.
> There's a learning path on the O'Reilly platform here, is there more content to add?
> https://learning.oreilly.com/learning-paths/learning-path-innersource/0636920438137/

Technically the O'Reilly LP misses the integration with the articles and workbook. We've got the articles integrated in our hosting on our site and YT. WB integration still needed.

Considered was LI Learning, Udemy, ...

**Comment by rrrutledge** [comment]
That’s tru, @lenucksi

**Comment by rrrutledge** [comment]
We'd like to explore placing our content also at https://www.udemy.com/teaching/?ref=teach_header
