### ISSUE TITLE
Pull Request as term in Learning Path

### ISSUE THREAD

**Issue by MaineC** [InnerSourceCommons/InnerSourceLearningPath#291]
Pull Requests are GitHub specific terminology. InnerSource can work with other tooling as well, still we rely on Pull Requests as a term in the Learning Path. Do we need a Disclaimer around "we are using this term not to endorse this one tool, but because this terminology is widely known and understood which is why we use it here"?

**Comment by rrrutledge** [comment]
_BitBucket_ and _GitHub_ both use it, but not _GitLab_.

**Comment by MaineC** [comment]
I didn't know about BitBucket. Thanks for that clarification. So in a way our language is already following what could be called an "industry standard".

**Comment by rrrutledge** [comment]
I feel like we're OK.  _GitLab_ even [acknowledges the term](https://docs.gitlab.com/ee/topics/gitlab_flow.html#mergepull-requests-with-gitlab-flow) although they don't use it directly.
