### ISSUE TITLE
Validate the quality of the machine tranlsatiom using the introduction videos

### ISSUE THREAD

**Issue by lenucksi** [InnerSourceCommons/InnerSourceLearningPath#301]
We want to find out how good the quality of the machine translation of subtitles based on clean English subitles is. 
Let's do this to achieve it:

- Find 2 or 3 videos with good English subtitles
- Find native speakers for our largest target languages and ask them to watch it with subtitles and rate the translation quality.

We've thought about who we know that might have native non-English language skills and hence might have a good say on this topic. If any of you below would want to try this and have 5-10 minutes to spare you're more than welcome to do so.
- German: @arnom-ms, @RJPlog @MaineC @lenucksi 
- Spanish: @dicortazar 
- French: @danese
- Japanese: @ystk @johtani @shinobusaito
- Chinese: @niminghong @adadai88 @tanzhongyi003   
- Thai: @mishari

Everyone else is more than welcome to add their opinion too! :smile:

**Comment by lenucksi** [comment]
Hey everyone! 
We're currently trying options to provide language specific subtitles for our videos based on the great, manually created English subtitles by @marshmallowrobot (thanks for creating them!) 
YouTube offers to add auto-translated subtitles once some subtitles are present. We've ad-hoc validated the translation quality with a few videos and the native languages of whoever non-English-speaking person was there at the point (mostly German). 
Now we want to validate the quality of other translations. And we're looking for volunteers who are fluent-enough in English to understand the English subtitles, native or good enough in any other 2nd language and have about 5-10 minutes of their time to spend.

Here's what you'd need to do:
- Watch this video to learn how to switch on auto-translated subtitles: https://youtu.be/8p1lbacg-jE?t=97 (in case you don't already know how)
- Watch this video with the auto-translated subtitles or your choice: https://innersourcecommons.org/resources/learningpath/introduction/02/
- Tell us what you think about the quality of the subtitles with a rating from A-F (A: Excellent, F: Unvoluntarily funny) as comment here with the subtitle language included.

**Comment by mishari** [comment]
I just realized this task is easier if you mute the voice and see how well you can make sense of the subtitles.

I rate it a C; in the intro the word "feature" is translated to "experience" which makes things quite confusing.

**Comment by johtani** [comment]
Rating is C.
Basically, it is natural Japanese. However, there are some pain points
1. Overlapping subtitles on English subtitles / pictures
2. Two translated Japanese words for "experience" in subtitles.  It is hard to understand "experience" is team name sometimes.
3. Team names. In English, the word "team" is usually omitted. e.g. API (team) or Experience (team). So, sometimes "experience" and  "API" make some confusions in translation...

**Comment by rrrutledge** [comment]
Sounds like it’s better not to share the videos at this point - just the articles?

**Comment by lenucksi** [comment]
Thanks @mishari and @johtani for providing that estimation! 
Do you think it'd worthwhile to have those subtitles shown / activated if we embed the videos on our page given the quality you mentioned?

**Comment by ShinobuSaito** [comment]
Sorry for late response. I watched the videos with auto-translated subtitles in Japanese. My rating is C because I could catch on the most of Japanese subtitles been translated. I agree with the comments suggesting the word "experience" is hard to understand the name of team. However, transfer of argument omission in the speech is too difficult... 
If the overlapping problem is solved, my opinion that it might be worthwhile to show them.

**Comment by rrrutledge** [comment]
Thanks, @ShinobuSaito.  It sounds like a "C" all around.
