### ISSUE TITLE
Italian translation of "Contributor" section

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#307]
See [Translations](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/CONTRIBUTING.md#translations).

**Comment by lenucksi** [comment]
@openpj will be interested in this

**Comment by OpenPj** [comment]
Sure, you can count on me :)

**Comment by OpenPj** [comment]
I have just submitted the following pull request for this
https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/359
