### ISSUE TITLE
Cannot find content of learningpath page

### ISSUE THREAD

**Issue by WillemJiang** [InnerSourceCommons/InnerSourceLearningPath#325]
When I visited the [learningpath](http://innersourcecommons.org/resources/learningpath/introduction/)  from innersourcecommons website, I can only find the index table on the page, but I cannot find any content of the article. 

BTW, I cannot find any information about how to build the website from asciidoc. It's hard for me to dig deeper :(

**Comment by WillemJiang** [comment]
Now I can see the content, but it doesn't show the changes I made recently.

**Comment by rrrutledge** [comment]
Hi, Willem, things should be working.  Can you share which Chinese article has changes that you think should appear (but is not appearing)?

**Comment by WillemJiang** [comment]
My last PR about trusted committer which was merged three days ago, I can see master branch is updated, but the website is not updated.

**Comment by rrrutledge** [comment]
What change, specifically?  I see [this change](https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/314/files) which is definitely [here online]https://innersourcecommons.org/resources/learningpath/trusted-committer/zh/).  Which change do you not see?

**Comment by WillemJiang** [comment]
@rrrutledge  I just did a quick check and I can see all of my changes on the website.
Thanks for taking care of it, I can close this issue now.
