### ISSUE TITLE
Set up publishing to LinkedIn Learning

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#334]
Our learning content is so great.  We should get all prepped to publish it to LinkedIn Learning.

There is a form to apply to be an instructor here: https://learning.linkedin.com/instructors . They do not seem to contract with groups, but rather individuals - which suggests we would have to re-record for their platform (with an individual presenter) unless they can make an exception for ISC.  Their recording guidelines are here: - https://learning.linkedin.com/content/dam/me/learning/en-us/pdfs/li-learning-instructor-toolkit-guidelines-recording-sample-video-09-19-old.pdf
I think we definitely meet the bar in terms of quality!

We should fill in the form on behalf of Danese - if they accept, we can discuss options for multiple presenters.

**Comment by fioddor** [comment]
Not moved in over a year.
