### ISSUE TITLE
Set up publishing to Pluralsight

### ISSUE THREAD

**Issue by claredillon** [InnerSourceCommons/InnerSourceLearningPath#338]
Investigation Pluralsight as a potential publishing platform for Learning Path content

**Comment by claredillon** [comment]
Following a discussion with Pluralsight's Aquisitions Editor - we have an opportunity to create content for the Pluralsight platform. Note there is no option to publish content already available, this would be a new set of content commission by/for Pluralsight. If we would like to proceed, they have asked us to submit a proposal for a course that would fit their criteria:

Likely to be a 2 hour course.
Content has to be made specifically for Pluralsight, with their slide template. 
It usually would be delivered by one speaker, not a group.
They have a process which sounds similar to the O’Reilly process, requires a script with learning outcomes etc.
Courses are mostly broken down into small modules, 4-8 minutes in length.
Most of their content is just slides and voice-over, and doesn’t have a speaking head. But some of the content does have this.
Audio and visual tracks need to be presented separately.
Usual equipment ask is usually to have a pro mic and pop filter and to use Camtasia for any screen grabs, to highlight things on screen, and/or add in overlays. 
From a content perspective, it is suggested that we focusing on a particular problem / use case and discussing how to solve it and skills that would be useful (as opposed to a general overview of the topic). 

More details about the contracting arrangements will be shared on the Slack channel.

If we want to move ahead, next steps would be to:
If we choose to pursue this opportunity, the next step would be to reply with a proposal that includes:
Overview of InnerSource Commons
High-level proposed structure of a course (with learning outcomes)
Bio of the speaker we propose
Sample video material (an “audition” reel).

**Comment by rrrutledge** [comment]
When we create new content we could consider dual-recording it - one for PluralSight one general.
