### ISSUE TITLE
Translate "Contributor" articles to Japanese

### ISSUE THREAD

**Issue by tsadler1988** [InnerSourceCommons/InnerSourceLearningPath#339]
- [x] introduction

- [x] becoming a contributor

- [x] contributor ethos

- [x] mechanics of contributing

- [x] benefits of contribution

- [x] conclusion

**Comment by rrrutledge** [comment]
Thanks, Tom.

**Comment by rrrutledge** [comment]
Yoshi is working on presenting at the APAC summit - suggest following up after the summit.

**Comment by rrrutledge** [comment]
Yoshi presented at the summit and may pick this up again.

**Comment by rrrutledge** [comment]
Amazing work @ystk !!!
