### ISSUE TITLE
Automate publishing to innersourcecommons.org

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#349]
Every time there is a new article or a new contributor we need to manually run [these steps](https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/scripts#how-to-update-innersourcecommonsorg-with-new-articles) to publish on innersourcecommons.org.

We should automate this process so that it happens automatically every time there is a change to an article in the learning path.  Likely this should be done with GitHub actions.

**Comment by tsadler1988** [comment]
I think we did discussed this in an LP meeting, but we probably want to prioritise innersourcecommons.net. But it might then be easy to also do this for innersourcecommons.org.

**Comment by rrrutledge** [comment]
Yes, that makes sense.

**Comment by tsadler1988** [comment]
New site is live on innersourcecommons.org - previous references to innersourcecommons.net in this issue are obsolete.

**Comment by tsadler1988** [comment]
Started working on this in a fork: https://github.com/tsadler1988/InnerSourceLearningPath/actions/workflows/publish-to-website.yml.

**Comment by tsadler1988** [comment]
PRs opened for a first iteration:
- https://github.com/InnerSourceCommons/innersourcecommons.org/pull/130
- https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/426

Future improvements:
- Trigger on pushes to this repo instead of hourly (discussed in https://github.com/InnerSourceCommons/innersourcecommons.org/pull/130)
- Remove manual step of adding new languages to the website [config.yaml](https://github.com/InnerSourceCommons/innersourcecommons.net/blob/master/config.yaml)

**Comment by tsadler1988** [comment]
Changed the approach to have an Action in the Learning Path which builds the files and commits to a branch of innersourcecommons.org (#432) with a second action on innersourcecommons.org to raise the PR (https://github.com/InnerSourceCommons/innersourcecommons.org/pull/130).

Once #432 is merged and seen to be working, I would consider this issue ready to close.

Remaining manual steps we may want to address (both only occur when adding a completely new language):
- adding new languages to the website [config.yaml](https://github.com/InnerSourceCommons/innersourcecommons.net/blob/master/config.yaml)
- top-level _index pages ([example](https://github.com/InnerSourceCommons/innersourcecommons.org/pull/137))
