### ISSUE TITLE
"Incorporating InnerSource Into Sprints" Outline

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#350]
Per our [CONTRIBUTING.md](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/CONTRIBUTING.md) we should start this new segment with an [outline](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/outline-template.md).

**Comment by lenucksi** [comment]
@Ludmila-N might be interested in a collab here. Maybe there's an opportunity to collaborate here in creating an outline @rrrutledge

**Comment by Ludmila-N** [comment]
@rrrutledge @lenucksi - assume I start by creating the new folder at the root of the project, and place the new outline.md into that folder?
How do we want to name it? /sprints doesn't look very clear, and /incorporating-into-sprints is a tad too long...
What about /day2day or /practical-implementation?
Else please suggest/vote

**Comment by Ludmila-N** [comment]
@rrrutledge are you open to additional ideas on top of your clear and basic guide? 
We can always trim them off if you feel they are not widely applicable, or too restrictive.

**Comment by rrrutledge** [comment]
Sounds great.  I think that it should have the word `sprint` somewhere in the title. `incorporating-into-sprints` is a reasonable length in comparison with some of [our other sections](https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/trusted-committer).

**Comment by Ludmila-N** [comment]
@rrrutledge will "/sprint-implementation" fit the bill?
I want to keep the naming to the nouns, so that all sections read in a similar way. And "incorporation" sounds like legal/tax stuff... Hope "implementation" is ok with you?

**Comment by rrrutledge** [comment]
Sure, that works.

**Comment by Ludmila-N** [comment]
Resolved by #399
