### ISSUE TITLE
"Principles" Article

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#36]
This card tracks the work to create a written article to teach the universal, underlying principles of effective inner source.

The article should be PR'd to https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/introduction/principles.md

**Comment by rrrutledge** [comment]
See https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/44

**Comment by lenucksi** [comment]
#87 has the remaining unmerged discussion content from #44 as a PR.

**Comment by rrrutledge** [comment]
Thanks, Johannes.

**Comment by rrrutledge** [comment]
See https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/115 for an update.

**Comment by rrrutledge** [comment]
Left a few last suggestions at https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/128

**Comment by lenucksi** [comment]
Move to done, thus closing the ticket.

**Comment by rrrutledge** [comment]
🎉
