### ISSUE TITLE
Document how to add translated navigation elements

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#363]
We have the ability to add translated navigation text (e.g. "Next", "Previous", "Return to Home") to the segments published on innersourcecommons.org.

We should update the [instructions for adding a new language](https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/scripts#how-to-update-innersourcecommonsorg-with-new-articles) to include instructions on how to add these translated navigation elements.

**Comment by tsadler1988** [comment]
As mentioned in https://github.com/InnerSourceCommons/innersourcecommons.net/pull/32, this is even more important for the new website.

**Comment by voborgus** [comment]
In the new version, there are no "next" "previous" and "home" signs, buttons have names of the [sibling pages](https://innersourcecommons.net/learn/learning-path/introduction/01/):
![image](https://user-images.githubusercontent.com/9394918/107006878-d58bbd80-67a2-11eb-99e3-c1b391b0c4b8.png)

The only button with a static name is "Learn" ([layout here](https://github.com/InnerSourceCommons/innersourcecommons.net/blob/master/layouts/learn/list.html)) but this should be parametrized only the first time for all pages.

**Comment by rrrutledge** [comment]
So this is a non-issue in the new website?

**Comment by voborgus** [comment]
As I understand, yes.

**Comment by rrrutledge** [comment]
Since it's a non-issue in the new website let's close this and put our time into the new experience instead.
