### ISSUE TITLE
Translate "Trusted Committer" articles to Japanese

### ISSUE THREAD

**Issue by ystk** [InnerSourceCommons/InnerSourceLearningPath#367]
- [x] Introducing the Trusted Committer Role
- [x] Ensuring Product Quality
- [x] Keeping the Community Healthy
- [x] Upleveling Community Members
- [ ] Lowering the Barriers to Entry
- [ ] Advocating for the Community’s Needs
- [ ] Becoming a Trusted Committer
- [ ] Conclusion

**Comment by rrrutledge** [comment]
Hi, @ystk, this work has been great!  Let us know if you're thinking about continuing this translation.

**Comment by ystk** [comment]
Sorry for the long silence. @rrrutledge 
Yes, I will continue it. Just had a busy time in March and April.

**Comment by rrrutledge** [comment]
Amazing work, @johtani and @ystk ‼️ 🎉 🏆
