### ISSUE TITLE
Point LearningPath readers to the Patterns in the online book

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/InnerSourceLearningPath#373]
I looked at the LearningPath content, and noticed that there are some links to patterns. Those links point to the markdown files in the [InnerSourcePatterns](https://github.com/InnerSourceCommons/InnerSourcePatterns) repo.

Today we launched the book-version of our patterns at https://patterns.innersourcecommons.org.
Therefore I am wondering, if it would be good to change the links in the LearningPath, and point to the patterns in the online book, rather than to the GitHub repository?

If you agree with the approach, then I am happy to send a PR for this.

Why could that be useful?
* the links in the book are more stable i.e. less likely to break (in the examples below you will see some links that are already broken e.g. `contributor/outline.asciidoc`)
* the book comes with a prettier layout i.e. looks a bit more professional

## Examples of Pattern links in the Learning Path

```
contributor/03-contributor-ethos-article.asciidoc
75:sense to offer to fulfill a https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/30-day-warranty.md[30-day

contributor/it/03-contributor-ethos-article-it.asciidoc
68:senso offrire per soddisfare una https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/30-day-warranty.md[garanzia a 30 giorni]

contributor/ja/03-contributor-ethos-article-ja.asciidoc
51:あなたの投稿に対して、 https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/30-day-warranty.md[「30日間保証」] を付けることは理にかなっています。

contributor/outline.asciidoc
57:   **** Offer to fulfill a https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/30-day-warranty.md[30-day warranty] on your submission.

contributor/zh/03-contributor-ethos-zh.asciidoc
31:项目团队将接管你的代码进行维护。你得保证有 https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/30-day-warranty.md[_30天保修 _] 在你的提交记录里。这将缓解项目团队对于贡献者贡献代码以后不进行后续的bug修复的担心。

introduction/03-how-works.asciidoc
46:* The https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/patterns/2-structured/trusted-committer.md[Trusted Committer] pattern.

introduction/de/03-how-works-de.asciidoc
47:* Die Mustervorlage https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/patterns/2-structured/trusted-committer.md[Trusted Committer].

introduction/it/03-how-works.asciidoc
46:* Il pattern del https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/patterns/2-structured/trusted-committer.md[Trusted Committer].

introduction/ja/03-how-works-ja.asciidoc
47:* https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/patterns/2-structured/trusted-committer.md[トラステッドコミッター] パターン

introduction/ru/03-how-works.asciidoc
45:* https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/patterns/2-structured/trusted-committer.md[Trusted Committer] паттерн.

introduction/zh/03-how-works-zh.asciidoc
20: * https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/patterns/2-structured/trusted-committer.md[Trusted Committer] 的模式。

workbook/04-contributor.asciidoc
71:You should plan to be available at a minimum to fulfil a https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/patterns/2-structured/30-day-warranty.md[30-day warranty] on your changes (and their impact), or even better: stay close to the community and help out with additional contributions.
```

**Comment by rrrutledge** [comment]
This sounds great please do.

**Comment by spier** [comment]
Done (see #374).

Just a follow-up question as it is related:
If there are other places in the learning path where it could we helpful to link to Patterns, how could one go about adding those? Is it that I would start with the English version, and if those changes get approved+merged, they are slowly ported into the translations over time?

**Comment by spier** [comment]
@rrrutledge the specific issue reported here is already solved now, so we can already close the issue if you like. 

Shall I file a new issue for the last question above?

**Comment by rrrutledge** [comment]
We haven't had any modification to the English files since translations started.  If you have a proposal to make then we can work with you on the best way to get it into all of the translations.

**Comment by rrrutledge** [comment]
And, yes, a new issue would be the best way to work on that together.

**Comment by spier** [comment]
Created a new issue. Closing this one.
