### ISSUE TITLE
Decide upon a spelling of 'InnerSource' vs. 'inner source' within the articles and clean up accordingly.

### ISSUE THREAD

**Issue by lenucksi** [InnerSourceCommons/InnerSourceLearningPath#39]
As mentioned in PR #38 and discussed on [Slack](https://paypalflow.slack.com/archives/CARTU4XV2/p1549613024083900?thread_ts=1549581428.081200&cid=CARTU4XV2) we need to decide which spelling to use - either 'InnerSource' or 'inner source'.
After deciding on that we'll need to clean up the articles respectively. 

Let's use this ticket to coordinate / bundle all related matters, i.e. close this
- once the decision is made **AND**
- all files are cleaned up accordingly.

**Comment by rrrutledge** [comment]
Thanks for opening, @lenucksi

**Comment by rrrutledge** [comment]
In the last InnerSource Commons Governance meeting we said that we would try out using InnerSource (1 word) in its noun form only.  When a verb is needed we could go through and pair another verb with the noun InnerSource (e.g. "adopting InnerSource" instead of "InnerSourcing").

**Comment by fioddor** [comment]
For reference:
- https://www.youtube.com/watch?v=6nFNnDKTQlg
- https://github.com/jeffabailey/InnerSourcePatterns/blob/main/meta/innersource-spelling.md

**Comment by rrrutledge** [comment]
Thank you!

just curious … how did you find this?
