### ISSUE TITLE
Translate "Introduction" articles to French

### ISSUE THREAD

**Issue by lenucksi** [InnerSourceCommons/InnerSourceLearningPath#397]
- [ ] Introduction
- [ ] Problems solved
- [ ] How works
- [ ] Benefits
- [ ] Principles
- [ ] Conclusion

Discussion had it that a person said they would be fine reviewing machine translated content for a French version. Hence, I'm raising this issue and will follow it up with a machine translated version.

**Comment by tsadler1988** [comment]
This is done and live on the website 🎉  - https://innersourcecommons.org/fr/learn/learning-path/introduction/

**Comment by lenucksi** [comment]
The thumbnails actually all say introduction - probably that needs a fix.

**Comment by tsadler1988** [comment]
Don't think that's specific to French nor the Introduction section e.g. https://innersourcecommons.org/learn/learning-path/contributor/ all the thumbnails say The Contributor, but they are different images for the different videos.
