### ISSUE TITLE
Translate "Product Owner" articles to Japanese

### ISSUE THREAD

**Issue by ystk** [InnerSourceCommons/InnerSourceLearningPath#407]
- [x] Opening
- [x] How Difficult it is to be Middle Management
- [x] Major Benefits are Built into the InnerSource Process
- [x] New Roles and Responsibilities
- [x] Recap and Takeaways
- [x] Closing

**Comment by ystk** [comment]
This issue was resolved.

**Comment by rrrutledge** [comment]
Amazing work, Yoshi!!
