### ISSUE TITLE
Add hyperlinks to all the articles, use the respective articles' GitHub location as link target. 

### ISSUE THREAD

**Issue by lenucksi** [InnerSourceCommons/InnerSourceLearningPath#41]
In our last LP call on 2019/2/14 (see Google Docs) we heard from O'Reilly that they support hyperlinks to other LP parts or outside web pages in their LP format. (Yay! 👍 ) 
Once we know how to annotate them inside the documents we need to go through or textual resources and actually add all the hyperlinks we want. Let's use this ticket to track that.

**Comment by lenucksi** [comment]
Outcome of our call on the 28th of February:
O’Reilly will add active hyperlinks during production.  Prior to that time we can add GitHub markdown links.  When we need to link to another article we can link to the GitHub location of the article (for now).

**Comment by rrrutledge** [comment]
Currently the articles are basically done for the [Introduction](https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/introduction) and [Trusted Committer](https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/trusted-committer) sections.  We can start by adding hyperlinks between those.

**Comment by hpdang** [comment]
@rrrutledge i can work on this

**Comment by rrrutledge** [comment]
Fantastic, @hpdang - happy to have you do so!  Please assign to yourself and move to `In Progress` on the [project board](https://github.com/InnerSourceCommons/InnerSourceLearningPath/projects/1)?

**Comment by Ludmila-N** [comment]
@rrrutledge @lenucksi and anyone else with strong opinion: please weigh in on these questions  before I make too many changes:
1.Destinations for the links: I was linking references to the role folders, i.e. "Contributor" word would link to https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/contributor,  etc.
Do I instead need to link to specific .md files, such as https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/01-introduction-article.md?
2. The markup is different in different articles, ie "Contributor" word is in **bold** in the intro section, but in _italics_ in the Trusted Committer section. I'd like to change it all to italics for consistency - any objections?
3. The articles are reasonably short - do we want links from EVERY occurrence of Contributor, Trusted Committer or Product Owner words, or the FIRST TIME they occur in a given article (plus of course will add links to any specific references such as "please see XX section")?  
Appreciate your guidance/opinion!

**Comment by rrrutledge** [comment]
Thanks for this comment, Ludmila.  I'll weigh in with my thoughts.

1.  I think that we should link to specific articles (`.md` files) for now.
1.  Sounds good to me.
1.  I like your suggestion of first time only.

**Comment by Ludmila-N** [comment]
Thanks @rrrutledge! Another question: this article https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/introduction/04-benefits.md has the following link to the learning path in the first paragraph:
https://www.safaribooksonline.com/learning-paths/learning-path-lean/9781491999738/9781491946527-/part01ch01.html - it is not publicly available and goes into"Start free trial". Are we OK with this?

**Comment by Ludmila-N** [comment]
@rrrutledge I fat-fingered my pull request https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/146 - meant to merge it to my own fork but it somehow got merged to the main repository. 
I completed the links in the intro section - wanted someone to give it a quick review but did not mean to merge. Now I don't want to revert it either, as to not to cause more trouble. 
1. Please let me know if OK to keep the links
2. Who can hive it a quick review so I can adjust the work in the other sections if needed?

**Comment by Ludmila-N** [comment]
All, there's an article missing under the contributor section: 04-mechanics-of contributing.md is not there. Does anyone have the draft?

**Comment by rrrutledge** [comment]
> it is not publicly available and goes into"Start free trial". Are we OK with this?

Opened https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/149 to remove.

**Comment by rrrutledge** [comment]
> Who can hive it a quick review so I can adjust the work in the other sections if needed

We can just keep this ticket in review and add comments to the merged PR.  You can just address the comments in a new PR with the same responsiveness as if they had appeared on the original PR.

**Comment by rrrutledge** [comment]
> 04-mechanics-of contributing.md is not there. Does anyone have the draft?

Looks like it's been merged - https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/04-mechanics-of-contributing.md

**Comment by rrrutledge** [comment]
> You can just address the comments in a new PR with the same responsiveness as if they had appeared on the original PR.

Added a few comments to https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/146.

**Comment by rrrutledge** [comment]
Also I added a requirement to the repo for pull requests to have a reviewer.

**Comment by lenucksi** [comment]
I agree with @rrrutledge [responses](https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/41#issuecomment-540815657) to your questions [here](https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/41#issuecomment-540805010).

Also, thanks for finding all these inconsistencies and other small glitches! :D
Referencing the links at our site will allow convert them easier for different hosting variants/renderings a lot, too.

**Comment by Ludmila-N** [comment]
Questions again... I'm reading the Trusted Committer articles, and they call Trusted Committers "TCs"  (repeatedly of course, because that's who the articles are about!)
How are you all feeling about replacing TC with "Trusted Committer" for readability? OR was this done on purpose to introduce and reinforce the use of this abbreviation?

**Comment by lenucksi** [comment]
> Questions again... I'm reading the Trusted Committer articles, and they call Trusted Committers "TCs" (repeatedly of course, because that's who the articles are about!)
> How are you all feeling about replacing TC with "Trusted Committer" for readability? OR was this done on purpose to introduce and reinforce the use of this abbreviation?

Good question.From my point of a view replacing the abbreviations with the full term would be OK.

**Comment by Ludmila-N** [comment]
@lenucksi @rrrutledge and all,
I have finished adding links and made minor grammatical fixes along the way (plural/singular, upper/lower cases, commas etc.).
I am still unhappy with the style of some articles, most likely the ones that are transcripts of the videos. We have an overload of "such", "this", "that", "also" and "even". 
Examples are "**what this comes down to is that...**", or the whole sentences like "**It has a lot of benefits in regards to that.**" 
Additionally, we have repeated sentences that sound OK in a video, but make an article look unprofessional.
Are O'Reilly editors fixing the style? If not, I can do another quick run through all articles and smooth a few places. **Please let me know** - I should be able to complete this quickly if I have your go-ahead.

**Comment by lenucksi** [comment]
> @lenucksi @rrrutledge and all,
> I have finished adding links and made minor grammatical fixes along the way (plural/singular, upper/lower cases, commas etc.).

Thanks! :+1: 
Will likely have time for a review after the 30th.

> I am still unhappy with the style of some articles, most likely the ones that are transcripts of the videos. We have an overload of "such", "this", "that", "also" and "even".
> Examples are "**what this comes down to is that...**", or the whole sentences like "**It has a lot of benefits in regards to that.**"
> Additionally, we have repeated sentences that sound OK in a video, but make an article look unprofessional.
> Are O'Reilly editors fixing the style? If not, I can do another quick run through all articles and smooth a few places. **Please let me know** - I should be able to complete this quickly if I have your go-ahead.

If you are referring to the [Product Owner](product-owner) articles with the "transcripts": Those are raw material and were meant to serve as starting points for the Product Owner articles that are to be made.
We'll need an outline for those to begin with #15 and can then turn those articles into something better.
In my opinion I would let them sit until we know where we want to go with the Product Owner articles.

**Comment by rrrutledge** [comment]
I will take a look as well.

**Comment by rrrutledge** [comment]
@Ludmila-N is it correct that the ones you are unhappy with are Product Owner?  I agree with that.  No one has really tried to write a real article for them, yet.

The Trusted Committer articles also follow the spoken word very closely, but they seem better to my view.

**Comment by Ludmila-N** [comment]
> @Ludmila-N is it correct that the ones you are unhappy with are Product Owner? I agree with that. No one has really tried to write a real article for them, yet.
> 
Mostly Product Owner, and thank you both for the history. But also some parts of the contributor section, namely [03-ethos](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/03-contributor-ethos-article.md) and [04-mechanics](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/04-mechanics-of-contributing-article.md)
If you don't mind, I can try a few streamlining strokes and let you accept or reject it. Let me know.

**Comment by Ludmila-N** [comment]
Oh and this specific issue #41 should be closed with this PR - what's the procedure for final review and closure?

**Comment by lenucksi** [comment]
> Oh and this specific issue #41 should be closed with this PR - what's the procedure for final review and closure?

Once the PR gets merged and no-one has any questions any more the ticket goes into the closed state.

**Comment by rrrutledge** [comment]
Someone has to remember to manually close the ticket, but yes.
