### ISSUE TITLE
Plan for Embed-able Content Feed

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#441]
Some people want to embed learning path content into their internal portals.  How can we package up the learning path so that companies can do that?

**Comment by clcoffey** [comment]
I'm having a meeting tomorrow afternoon to discuss requirements, I will let you know more details then.

**Comment by rrrutledge** [comment]
Sounds good - thanks for this work!

**Comment by clcoffey** [comment]
Clare and I have had a meeting with one company last week around this and we are in the requirements gathering phase. We also have a second company that has expressed an interest and we will schedule a meeting with them as well. 

It is very likely this will be a long project and I won't have any concrete updates until October.

**Comment by rrrutledge** [comment]
Thanks for this update, Cristina!  Let us know what you find.

**Comment by rrrutledge** [comment]
OK thank you!

**Comment by rrrutledge** [comment]
Translated learning path content may not be sold.

**Comment by rrrutledge** [comment]
@clcoffey is there any more work to do here?

**Comment by rrrutledge** [comment]
Meeting scheduled on 1 March to discuss.

**Comment by rrrutledge** [comment]
We did meet.  Our representative was interested in how to contribute generally to the ISC.  Could be patterns or learning path, depending on what is needed.   What I think we need is to set up some kind of liaison to their company ISPO that stays in touch regularly and directs contributions to the appropriate place.

**Comment by tsadler1988** [comment]
Liaisons with other companies sounds like an exciting idea!

Closing this as an embeddable content feed is not a requirement.
