### ISSUE TITLE
Signed amendment for video release

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#46]
DESCRIPTION

Currently the videos that we're producing are exclusively hosted in the O'Reilly Safari learning platform.  We're so glad that the content is there!  However, not all members of the InnerSource Commons have access to them.

We want O'Reilly to release the videos to the InnerSource Commons so that they can be hosted at a location where all members can see them.

In order to do so, PayPal needs to sign an updated contract consistent with the above-stated intent.  The purpose of this card is to track that work happening.

ACCEPTANCE CRITERIA

There is a signed contract for the Learning Path that allows for release of the produced videos to the InnerSource Commons.

**Comment by clobner** [comment]
The amendment is with PayPal awaiting signature. The O'Reilly account manager is aware that we'd like to have the videos released in advance of the summit, and we're continuing to follow up with that timeline in mind. My goal is to have the signed agreement in place by 3/15.

**Comment by rrrutledge** [comment]
Fantastic update, Colleen!

**Comment by lenucksi** [comment]
#66 also relates to this / is blocked by it.

**Comment by clobner** [comment]
Exciting news! This amendment was signed yesterday, so we can now move forward with releasing the Learning Path videos.

**Comment by lenucksi** [comment]
This is really fantastic news!

**Comment by rrrutledge** [comment]
By the acceptance criteria in this issue it should be moved to `Done` ❓

**Comment by lenucksi** [comment]
> By the acceptance criteria in this issue it should be moved to `Done`

And by being in ```Done``` it should also be closed.

**Comment by rrrutledge** [comment]
🎉 Thank you! 🎉
