### ISSUE TITLE
Translate Trusted Committer section into French

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#460]
The goal is to have all 8 French articles for [Trusted Committer](https://innersourcecommons.org/learn/learning-path/trusted-committer/)

- [x] [01-introduction.asciidoc](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/trusted-committer/01-introduction.asciidoc)
  - [x] Tease
  - [x] Correct language 
- [x] [02-ensuring-product-quality.asciidoc](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/trusted-committer/02-ensuring-product-quality.asciidoc)
  - [x] Tease
  - [x] Correct language 
- [x] [03-keeping-the-community-healthy.asciidoc](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/trusted-committer/03-keeping-the-community-healthy.asciidoc)
  - [x] Tease
  - [x] Correct language 
- [x] [04-uplevelling-community-members.asciidoc](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/trusted-committer/04-uplevelling-community-members.asciidoc)
  - [x] Tease
  - [x] Correct language
- [x] [05-lowering-the-barriers-to-entry.asciidoc](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/trusted-committer/05-lowering-the-barriers-to-entry.asciidoc)
  - [x] Tease
  - [x] Correct language
- [x] [06-advocating-for-the-communitys-needs.asciidoc](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/trusted-committer/06-advocating-for-the-communitys-needs.asciidoc)
  - [x] Tease
  - [x] Correct language
- [x] [07-becoming-a-trusted-committer.asciidoc](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/trusted-committer/07-becoming-a-trusted-committer.asciidoc)
  - [x] Tease
  - [x] Correct language
- [x] [08-conclusion.asciidoc](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/trusted-committer/08-conclusion.asciidoc)
  - [x] Tease
  - [x] Correct language

Once the translations are created (even if not correct and preferably when **all** are there), the links must be reviewed and redirected to the french versions:
- [ ] [01-introduction-fr.asciidoc](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/trusted-committer/01-introduction-fr.asciidoc)
- [ ] [02-ensuring-product-quality-fr.asciidoc](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/trusted-committer/02-ensuring-product-quality-fr.asciidoc)
- [ ] [03-keeping-the-community-healthy-fr.asciidoc](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/trusted-committ/03-keeping-the-community-healthy-fr.asciidoc)
- [ ] [04-uplevelling-community-members-fr.asciidoc](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/trusted-committer/04-uplevelling-community-members-fr.asciidoc)
- [ ] [05-lowering-the-barriers-to-entry-fr.asciidoc](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/trusted-committer/05-lowering-the-barriers-to-entry-fr.asciidoc)
- [ ] [06-advocating-for-the-communitys-needs-fr.asciidoc](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/trusted-committer/06-advocating-for-the-communitys-needs-fr.asciidoc)
- [ ] [07-becoming-a-trusted-committer-fr.asciidoc](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/trusted-committer/07-becoming-a-trusted-committer-fr.asciidoc)
- [ ] [08-conclusion-fr.asciidoc](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/trusted-committer/08-conclusion-fr.asciidoc)

**Comment by tsadler1988** [comment]
Hi @SJVle, we were talking about doing this via machine translations as per #414. If we did this, would you be interested in reviewing it again? No problem if not, we can focus on other languages if we don't have a French speaking reviewer lined up 🙁 .

**Comment by SJVle** [comment]
Hi @tsadler1988 Ok, I could review Trusted commiter. I'm not so used with Github, so wich file I had to read ?

**Comment by tsadler1988** [comment]
Thanks @SJVle! We haven't created the machine translations yet, we will tag you when we do.

**Comment by rrrutledge** [comment]
@tsadler1988  can you remind us what is the script to check the links?

**Comment by rrrutledge** [comment]
@nysenthil to connect with @rrrutledge when his time frees up to run the "link checker" script.

**Comment by rrrutledge** [comment]
We suspect @nysenthil time may free up sometime in November to look at this.
