### ISSUE TITLE
Plan for IBM Watson powered translations to the learning path.

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#468]
Folks at IBM are willing to contribute internal resources (Watson translator) for ISC content.  We should figure out what is available and come up with a plan for what we are going to do to leverage those resources toward the learning path.

The plan should be encapsulated in a set of cards here on the board that we can review together.

**Comment by tsadler1988** [comment]
For now we will be using this manually. In the future we may want to explore automation if IBM are able to expose an endpoint.

**Comment by tsadler1988** [comment]
Duplicate of #472
