### ISSUE TITLE
Spanish translation of "Benefits of Becoming an InnerSource Contributor"

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#469]
Translate [Benefits of becoming an InnerSource Contributor](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/05-benefits-of-contribution-article.asciidoc) to Spanish ([Contributing Guidelines](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/CONTRIBUTING.md#translations)).

**Comment by fioddor** [comment]
This was already done and [published.](https://innersourcecommons.org/es/learn/learning-path/contributor/05/).
