### ISSUE TITLE
Shoot Playbook

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#47]
Before filming O'Reilly needs us to fill out this [shoot playbook](https://docs.google.com/spreadsheets/d/10SMX0NE20Y_6_z2BguKc-TLl8hartJKMJYXcqsSI09M/edit?usp=sharing).
This [author kit](https://app.oreilly.com/authors/welcomekit/video.csp) has an instructional video on the shoot playbook.

**Comment by rrrutledge** [comment]
@clobner which of the columns do we need to fill out? They're not all self-explanatory and some of them appear to be geared toward O'Reilly staff instead of the content author.

**Comment by clobner** [comment]
Hi @rrrutledge – We realized that the playbook template we provided was a newer version. Our learning team has approved us moving forward with the older template to align with the previous videos. I think this will be more straightforward to complete.

Please instead use [this playbook template](https://docs.google.com/spreadsheets/d/10SMX0NE20Y_6_z2BguKc-TLl8hartJKMJYXcqsSI09M/edit?usp=sharing) for the Contributors video.

Here's the [Trusted Committer playbook](https://docs.google.com/spreadsheets/d/1TJnrCIudz-R2EA_sresxSxXe5wRvGZKHu2M5Jy_22uM/edit?usp=sharing) for reference.

**Comment by rrrutledge** [comment]
Thanks, that playbook looks more familiar.

**Comment by rrrutledge** [comment]
Take a look at this [shoot playbook](https://docs.google.com/spreadsheets/d/10SMX0NE20Y_6_z2BguKc-TLl8hartJKMJYXcqsSI09M/edit?usp=sharing) and leave any comments here in the issue.

**Comment by lenucksi** [comment]
- The descriptions in C8/C9 look somewhat similar/too non-distinct to me (mindset and habits vs. how to behave (i.e. the execution following the mindset and single instances of habits))

**Comment by rrrutledge** [comment]
The distinction that we're trying to draw is more about the phase of work in-which the content applies.  C8 is about how to _become_ an InnerSource Contributor in the first place whereas C9 describes how to behave _as_ an InnerSource Contributor.

**Comment by lenucksi** [comment]
Re-Read it and I agree with you. It's actually phrased in a good way. Looks like a case of too little time taken by me to read it properly. Thus :+1: from me.

**Comment by rrrutledge** [comment]
Thanks!

**Comment by lenucksi** [comment]
Closing it, since it is in 'Done' now.

**Comment by rrrutledge** [comment]
Great!
