### ISSUE TITLE
Update “What is InnerSource” to “How does InnerSource work?”

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#48]
We're talking about [this video](https://www.oreilly.com/library/view/introduction-to-innersource/9781492041504/video321608.html).  We like the latter title better.

"Update"  means:
* The title in the O'Reilly UI.
* The introductory slide.

**Comment by clobner** [comment]
This work is in progress; I'll update the ticket when the update is in place.

**Comment by rrrutledge** [comment]
Thanks for this update, @clobner.  We incorporated your comment into the meeting and moved this issue to `In Progress`.

**Comment by clobner** [comment]
@rrrutledge This update is now live on the platform:

[https://learning.oreilly.com/videos/introduction-to-innersource/9781492041504/](https://learning.oreilly.com/videos/introduction-to-innersource/9781492041504/)

**Comment by rrrutledge** [comment]
💰.  Thanks, @clobner!
