### ISSUE TITLE
Check in updated links to GitHub

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#538]
The [publish script](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/main/.github/workflows/publish-to-website.yml#L29) that runs on each checkin does a local update of translated links.

We should update the publish script to also commit the results of the script run back into the `InnerSourceLearningPath` repo.

**Comment by tsadler1988** [comment]
This should be complete as of https://github.com/InnerSourceCommons/InnerSourceLearningPath/commit/a8b02d22c2439fdc08ff7fc84591ac3f2875608b. Tested via https://github.com/InnerSourceCommons/InnerSourceLearningPath/commit/63ddd5dae184200b1343255f6e524cc289c0a6c3  which resulted in https://github.com/InnerSourceCommons/InnerSourceLearningPath/commit/19f718ddf64e8c81c3261bbabed249798241b70e and it looks good!

Also fixed an issue where there is nothing to commit the build would fail, so made the commit and push conditional based on the presence of changes - see https://github.com/InnerSourceCommons/InnerSourceLearningPath/commit/4b03fb932e17ee380c755154822387ff2a353329.

**Comment by tsadler1988** [comment]
> You manually put this deploy key in the repo settings?
Yes that's right. There's no way of securely doing it in source control or with automation that I know of. I generated the key on my machine and deleted it once uploaded to GitHub.

**Comment by rrrutledge** [comment]
OK sounds great!  Thanks, Tom!
