### ISSUE TITLE
Polished content outline

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#56]
We have [the raw content](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/outline.md) of what we'd like to go in the _Contributor_ section.  Now we need to refine and polish that brain dump into a set of individual segments, each with a descriptive title and also a clear outline of what is in the section.  These titles/outlines should be descriptive and complete enough for us to fill out the [shoot playbook](https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/47), [video proposal](https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/49), and also to start drafting the written articles.

**Comment by rrrutledge** [comment]
Working at https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/contributor/outline/contributor/outline.md

**Comment by rrrutledge** [comment]
Please review https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/59

**Comment by rrrutledge** [comment]
https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/64 has some additional changes.

**Comment by lenucksi** [comment]
Closing this one since it is in 'Done' now.
