### ISSUE TITLE
Publish Written Articles

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#58]
Now that the [Trusted Committer Videos](https://learning.oreilly.com/videos/the-trusted-committer/9781492047599) are out there we need to publish the [written articles](https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/master/trusted-committer) as well.  We'd like each article to occupy its own page in the Learning Path.

**Comment by rrrutledge** [comment]
When the PDFs of the articles are available you can just attach them to this issue and move to `In Review`.

**Comment by rrrutledge** [comment]
@clobner I followed up on who should be listed as author on the _Trusted Committer_ written articles.

I looked through the _Git_ history and it @gruetter and I are the only committers to the articles.  We talked about it and Georg should be listed as the primary author and myself secondary.

**Comment by lenucksi** [comment]
From the point of initially reviewing the material living in all the branches, forks and merge request discussions I think there might have been additional reviews / contributions from others to the TC articles that we might want to give credit to in a way. 
Especially review-contributions from times before our use / the existance of the commit suggestion feature might be relevant here - hoping that the CS feature would ensure attribution for current work.
For example, I've found 42fb5521f2ab62ed72a728406d887a6faf4ab626 crediting Cedric and Loren for contributions to the TC article.

I know that this might be a quite a bit of work, but wanted to bring it on. After all praising participants and giving credit is one of our patterns...

**Comment by rrrutledge** [comment]
Sure!  Suggestions?

**Comment by clobner** [comment]
Articles are with the O'Reilly content team for review.

**Comment by lenucksi** [comment]
Went through the already merged PRs on the Trusted Committer and found these review contributions which appear to have had rather large effects on the resulting document.
- Cedric Williams, Noah Cawley #1 
- Guy W. Martin, Russ Rutledge #26 
- Loren Sanz, Cedric Williams, Erin MB #18 
- Erin MB, Tim Yao, Loren Sanz, Cedric Williams #9 (Reviews, pretty active PR)

> Sure! Suggestions? I know that you yourself have been a prolific reviewer in general though I can't recall how far along was the Trusted Committer work when you came on board?

The first PR activity I found was in January / February with #1 and #35 has been created due to me finding a typo on the slides (I think that's been the result of my initial review process).

**Comment by rrrutledge** [comment]
Great!  Per our previous conversations we should reach out to each to see if they'd like to be listed as a reviewer.

**Comment by lenucksi** [comment]
> Great! Per our previous conversations we should reach out to each to see if they'd like to be listed as a reviewer.

True, I'll do by mention and Slack.

**Comment by lenucksi** [comment]
Here's the outcome of the reach-out:
@NewMexicoKid 
@mrsanz 
@guywmartin 
replied to my reach-out and want to be listed as reviewer.

**Comment by rrrutledge** [comment]
From @clobner:

```
We've completed the copyedit of the Trusted Committer Role in InnerSource, and the file is now available for you to begin your review. 

Please use the Comment tools in Adobe Acrobat Reader or Pro to review and mark the PDF (please DO NOT use Mac Preview, as this often corrupts files and causes production delays). 

Please respond to any queries Christina has for you at that time and mark any edits you wish not to make as "Rejected." Feel free to add changes during this review as well. Most of Christina's edits will be minor grammar/style changes, which can be skimmed over. You can find more information about our conventions in the O'Reilly Style Guide.

If you have any questions, please feel free to reach out here or on Slack.
```
[The_Trusted_ComitterCE.pdf](https://github.com/InnerSourceCommons/InnerSourceLearningPath/files/3473516/The_Trusted_ComitterCE.pdf)

**Comment by lenucksi** [comment]
The PDF looks very nice :D @clobner 
Thanks also for the various edits. I agree with the need of the sub headings mentioned in one comment. I'll see if I can add some.

**Comment by gruetter** [comment]
Here's the PDF with my feedback in it.

[The_Trusted_ComitterCE_feedback_GG.pdf](https://github.com/InnerSourceCommons/InnerSourceLearningPath/files/3531026/The_Trusted_ComitterCE_feedback_GG.pdf)

**Comment by clobner** [comment]
This set of articles is now ready for final review. Here is the PDF:

[Trusted_Committer_Article_ QC1.pdf](https://github.com/InnerSourceCommons/InnerSourceLearningPath/files/3631718/Trusted_Committer_Article_.QC1.pdf)

**Comment by lenucksi** [comment]
Remaining work: Add the correct hyerlinks as discussed in #41.

**Comment by rrrutledge** [comment]
Latest from O'Reilly
[Trusted_Committer_Article_ QC1.pdf](https://github.com/InnerSourceCommons/InnerSourceLearningPath/files/3636939/Trusted_Committer_Article_.QC1.pdf)

**Comment by rrrutledge** [comment]
My comments: 
[Trusted_Committer_Article_ QC1.pdf](https://github.com/InnerSourceCommons/InnerSourceLearningPath/files/3702415/Trusted_Committer_Article_.QC1.pdf)

**Comment by lenucksi** [comment]
The existing comments are in the Atlas repo in ASCIIdoc format represent the edits. We'll merge those into our repo and once the pull request resulting from this merges we consider this content final.

**Comment by rrrutledge** [comment]
Publishing these articles blocked on [getting the final O'Reilly edits into _GitHub_](https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/157).

**Comment by rrrutledge** [comment]
We'll just have videos and review question in O'Reilly.
