### ISSUE TITLE
Licensing of articles / videos / workbook

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#66]
A potential contributor asked what is the license for the videos, articles, and workbook.  We don't have one right now, but should.

**Comment by rrrutledge** [comment]
Before actually adding a license to the repo we should get the 👍 from everyone that has contributed thus far.

**Comment by lenucksi** [comment]
- Discussion started in the Slack [here](https://paypalflow.slack.com/archives/CARTU4XV2/p1555713048041400) 
- Current suggestions revolve around CC BY-SA, something that is also used by the [patterns community](https://paypalflow.slack.com/archives/CARTU4XV2/p1555772253045700).

**Comment by rrrutledge** [comment]
Even though the ultimate destination of this content is O'Reilly media, we believe that the community is free to license these pre-production documents as makes sense.

At the same time, we want to make sure that any licensing applied to the documents in this repo don't inhibit their use by O'Reilly media.  We are thinking of the `CC-BY` or `CC-BY-SA` licenses and are curious for any input from O'Reilly with an eye to making sure that we can still continue to work well together.

**Comment by rrrutledge** [comment]
No matter what happens with [Signed amendment for video release](https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/46) It's hard to imagine that O'Reilly would seriously be interested in anything other than `CC-BY` (out of the two options above).

**Comment by clobner** [comment]
Quick update: I'm awaiting guidance from the O'Reilly team on whether it's safe to proceed with the `CC-BY` license. We're in discussions about how to proceed with this content program as a whole, and I've brought this topic into the conversation.

**Comment by rrrutledge** [comment]
One thing that was mentioned in today's governance meeting call was the idea of dual-licensing the content.  We want O'Reilly to still be able to fulfill their commercial interest in the content while encouraging others to contribute back any iterations of knowledge that are generally-applicable.

**Comment by rrrutledge** [comment]
For example, we wouldn't want some kind of InnerSource consulting company to take the content, create their own private derivatives, then never come back to interact with the community.

**Comment by clobner** [comment]
I've received a response from our VP of content on this item (thanks for your patience!):

> Generally, we would not allow a CC BY-SA 2.0 as a quality control issue. In this case, I would be willing to do it if we make sure that nothing represents the O'Reilly Media brand. We will have no control over the derivatives and so would not want to represent our part in the creation. It would also not allow us to fulfill any translation requests we may get.

Happy to discuss further next week.

**Comment by rrrutledge** [comment]
Sounds great.  I feel like what is in the repo is owned by the community and then O'Reilly is making a derivative from that. Looking forward to talking.

**Comment by rrrutledge** [comment]
In the last call we suggested checking in CC-BY-SA and then letting O'Reilly submit whatever modifications they need.

**Comment by lenucksi** [comment]
We managed to merge the CC BY-SA 4.0 license text in, so this part is done. Remaining issues to be handled in a separate ticket.
