### ISSUE TITLE
Article: The Contributor in InnerSource

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#67]
We should produce a written article based on **The Contributor in InnerSource** section of the [_Contributor_ outline](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/outline.md).

The article should teach the same points as [The Contributor in InnerSource Video](https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/68).

**Comment by lenucksi** [comment]
Move to done, thus closing the ticket.
