### ISSUE TITLE
Video: Benefits of Contribution (Video 05)

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#75]
We should produce a video based on the **Benefits of Contribution** section of the [_Contributor_ outline](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/outline.md).

The video should teach the same points as the [Benefits of Contribution Article](https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/76).

**Comment by lenucksi** [comment]
Let's use these tickets to track the (post-)processing / O'Reilly Screenlight process for the individual videos. 
@clobner: Since they're currently being processed at O'Reilly we've assigned them to you for the time of the processing until the Screenlight hosting is available.

**Comment by rrrutledge** [comment]
Please review at this link: https://innersourcecommons.slack.com/archives/CARTU4XV2/p1575306827151600?thread_ts=1573840051.113600

**Comment by lenucksi** [comment]
Completed a first pass of review for this video.
