### ISSUE TITLE
Video: Conclusion (Video 06)

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#77]
We should produce a video based on the **Conclusion** section of the [_Contributor_ outline](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/outline.md).

The video should teach the same points as the [Conclusion Article](https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/78).

**Comment by rrrutledge** [comment]
Please review at this link: https://innersourcecommons.slack.com/archives/CARTU4XV2/p1575306827151600?thread_ts=1573840051.113600

**Comment by lenucksi** [comment]
Completed a first review pass over this video.
