### ISSUE TITLE
Article: Conclusion

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#78]
We should produce a written article based on the **Conclusion** section of the [_Contributor_ outline](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/outline.md).

The article should teach the same points as the [Conclusion Video](https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/77).

**Comment by lenucksi** [comment]
Got moved to done, thus closing this one.
