### ISSUE TITLE
Figure out filming location(s) and team for the Contributor videos

### ISSUE THREAD

**Issue by lenucksi** [InnerSourceCommons/InnerSourceLearningPath#82]
We discussed the filming of the contributor videos in Berlin. To gauge the suitability of the local resources for the purpose a small clip will be created and discussed with O'Reilly.

**Comment by lenucksi** [comment]
Feedback from O'Reilly is that local equipment will likely not suffice. Will create a small clip nevertheless. Equipment present has been communicated to O'Reilly, Details are also in [Slack](https://paypalflow.slack.com/archives/CARTU4XV2/p1558784914010400).

We now need to determine shooting location(s) and teams for the participating persons. Thus I've renamed the ticket (as I was planning a week earlier...)

**Comment by rrrutledge** [comment]
Current suggestion is Isabel and Johannes for the actors.

**Comment by lenucksi** [comment]
I agreed with @clobner that we'll arrange a call to figure out the details of filming in Berlin in will this with the outcome as well as report back in the weekly call.

**Comment by rrrutledge** [comment]
Thanks for the update.

**Comment by rrrutledge** [comment]
Email has been sent to coordinate studio time in Berlin.  Dates should be set with time for a rehearsal that the community can give feedback on.

**Comment by lenucksi** [comment]
Move to done, thus closing the ticket.
