### ISSUE TITLE
Shared Calendar for Learning Path invites

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#89]
As the community progresses and grows we'd like to be able to share the meeting [roles](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/meetings/roles.md) between active members.  One role that's not sharable right now [Scheduler](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/meetings/roles.md#scheduler) because the repeating calendar invite is sent from Russ's calendar, which only he can access.

We should come up with some kind of calendar/invite solution that allows _any_ interested community member to (potentially) act as [Scheduler](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/meetings/roles.md#scheduler).

**Comment by rrrutledge** [comment]
Check out this [conversation](https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/86/files/cef3cc0a61d01b73eddd8985676ddbd17f35525b#r290764663) for some ideas on this topic.

**Comment by lenucksi** [comment]
We're using the shared calendar approach since some weeks successfully. We've added the relevant steps to the role document. I think we're successfully done with this task.

**Comment by rrrutledge** [comment]
It has been great!  Thank you.
